### ISSUE TITLE
Too big margin makes hang-up CPU.

### ISSUE THREAD

**Issue by fmy** [diegomura/react-pdf#2083] opened 2022-11-15 09:19 UTC
**Describe the bug**
Too big margin styles like 1000 make rendering freeze.

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Go to [this repl](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e619da74e5400a8614b1a004f003619b006f19f22003a2848a3c80bec4e9878c8015ba2c004cb2c9e3002c8f30c00058f2a01e9c64a122def01dfdce8199959d80801b8c8a34120a4a0e4302070600195e3e4529c3030a0d580009c307930f1143935b43000b860cb8400cdc0a0529000bdaa600098005800683929312401056490f8c06a01c9805931f2a7fb851879f2f890c14440001c6a011800180e966075fa7422a200948b80a0b86800c4d50ac12df2f0a91150cc60dd892e400000)
2. Change marginTop to 1000 from 100.
3. Browser hang-up

**Expected behavior**
At least it should crash or timeout.

**Screenshots**
<img width="1099" alt="スクリーンショット 2022-11-15 18 22 38" src="https://user-images.githubusercontent.com/856469/201881116-43d08fed-8411-477d-9c1a-7802b8553b4a.png">

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS, Windows] both
 - Browser [e.g. chrome, safari] any browser and node environment
 - React-pdf version [e.g. v1.1.0] @react-pdf/renderer@3.0.1 & @react-pdf/renderer@2.1.1

**Comment by oviniciuslara** [comment] 2023-01-02 21:51
I have reproduced this as well

**Comment by jeetiss** [comment] 2023-01-02 23:37
the same with `fontSize`

**Comment by oviniciuslara** [comment] 2023-01-02 23:40
@jeetiss this seems to be a generic problem with everything that goes over the page space, there is a lot of similar issues.

The root cause of this should be tracked down to fix this permanently. Do you have any idea where the problem lay down?

**Comment by oviniciuslara** [comment] 2023-01-03 09:45
I saw two different problems with this package:

1) Crashes if some element is positioned out of the page or if it overflows the page.
2) Crashes if the actual page has a lot of content, thus using a lot of memory.

For static pages I think just adding a checker to verify if the element is inside the page is enough to avoid this situation, the problem is with dynamic content that could lead to the same situation. At least the package should throw an intuitive log about it, not crashing the entire browser.

About the memory limit we should also throw an intuitive log and ignore further elements before reached a memory limit.

Also, this is just a workaround based on simple analysis, accordingly to the root cause of this CPU crasher the solution may be different.

**Comment by oviniciuslara** [comment] 2023-01-03 09:50
@diegomura do you have any knowledge about this that could help?

I consider this issue a VERY HIGH since it affects rendering, the core of this package.

**Comment by kdubb1337** [comment] 2023-01-27 11:57
Related issue for me. I have a very long View that should be page wrapped, which works fine. But then when I add any padding to the containing Page it hangs.

**Comment by bezchristo** [comment] 2023-07-19 19:21
Getting the same issue when the image doesn't fit on one page.

**Comment by carlobeltrame** [comment] 2023-10-06 20:51
It's possible that the long element freeze could be fixed in #2400. I found some problems (including some potential infinite loops) in the page breaking algorithm there and was able to fix them. If anyone has the means to test that PR, would be highly appreciated.

**Comment by diegomura** [comment] 2024-02-03 18:06
Thanks @carlobeltrame . Since your PR change this logic considerably and we havent' heard again about this I'll close it. It can be opened again if someone says this still happens

**Closed by diegomura** 2024-02-03 18:06 UTC
