### ISSUE TITLE
Adding 'height' to `Text` fails when is lower than `fontSize`

### ISSUE THREAD

**Issue by web2wire** [diegomura/react-pdf#455] opened 2019-01-21 11:13 UTC
I am attempting to replicate a table layout and running into similar issues as other reports such as this (https://github.com/diegomura/react-pdf/issues/348) have described where text either doesn't appear or overlays other components.

One of the suggested solutions is to add a height to the css to assist the renderer. I have tried doing this however this causes an immediate crash. It is very simple to reproduce, just go to one of the examples at https://react-pdf.org/repl and add a height to the title or author css and you will get it.

The message varies, on Chrome it is ```Uncaught (in promise) TypeError: Cannot read property 'copy' of undefined``` but on FireFox it is completely different ```Unhandled promise rejection TypeError: "h[Math.min(...)] is undefined"```.

**Comment by diegomura** [comment] 2019-01-21 15:52
Could you post a snippet so I can reproduce this? Thanks!

**Comment by web2wire** [comment] 2019-01-21 18:14
Thanks for looking at this. The simplest way I can reproduce it is to go to your example page (https://react-pdf.org/repl) and change the author style to

    author: {
        fontSize: 12,
        textAlign: 'center',
        marginBottom: 40,
        height: 10,
    },

by adding the height css definition. Sometimes it seems to be able to render the PDF and other times it just says 'Rendering' forever. Either way you should see the error in the console. For my application that error is fatal, though the sandbox seems to be able to ignore it sometimes.

**Comment by web2wire** [comment] 2019-01-22 16:18
Thanks, I'm glad I wasn't imagining it :)

In my application the element where I am trying to set the height does not have an explicit font size defined, it inherits one defined on the Page element. In this case the font size is 9 but I still get the crash when I try and set the height to a larger value. Basically I'm trying to emulate a border-collapse style in a table by exactly lining up Text element heights and as the originally referenced issue points out the flex-direction row just overwrites other elements unless a height is explicitly set, though I have worked around it (I think) by using min-height which doesn't cause any crash issues.

**Comment by diegomura** [comment] 2019-04-14 18:09
This does not throw an error anymore. I still think that the current behavior is the expected: if you set up a fixed height to a Text and that's not enough to render it, nothing should render. After all, there's no enough space for it. Sometimes setting the exact height (or even some pt more) is not enough, since fonts have a `descent` distance defined. Closing this now

**Closed by diegomura** 2019-04-14 18:09 UTC
Labels: bug
