### ISSUE TITLE
Image: Base64 as src is broken

### ISSUE THREAD

**Issue by ostrgard** [diegomura/react-pdf#342] opened 2018-10-16 12:35 UTC
**OS:**
MacOS 10.14

**React-pdf version:**
1.0.0-alpha.18

**Description:**
Base64 as `Image` `src` is broken and throws `Couldn't fetch image: <string>`. `isomorphic-fetch`, which used `node-fetch` under the hood throws `Error: only http(s) protocols are supported`.

I suspect this commit, that implemented `isomorphic-fetch`: https://github.com/diegomura/react-pdf/commit/72d0454c0876c24386b7a37b53f39293ef3540d0, as it's younger than #216, which seems to conclude that this should be working as expected and documented in the docs.

**Suggested actions**
- [x] Somehow detect and handle base64 strings as `src`, as `node-fetch` simply does not support this. Maybe something like `Buffer.from(<string>, 'base64')`.
- [x] Properly output `node-fetch` errors for future debugging, instead of just `Couldn't fetch image: <string>`.
- [x] Add a base64 test case in `image.test.js`.

Alternatively, remove the instructions from the documentation, if this functionality is unwanted.

**How to replicate issue including code snippet (if applies):**
https://runkit.com/embed/uj7thrhoup3u

**Comment by jmelvin-r7** [comment] 2018-10-17 02:31
I also came across this same issue, and confirmed via other tools that my base64 image string was valid.

**Comment by kiranb555** [comment] 2019-11-26 12:29
<Image source = "data:image/svg+xml:base64,..../> this is not working to me.
Tried with src aswell same result not rendering an image.

**Comment by gavin771** [comment] 2019-12-13 01:17
same for me. No image is rendered.

**Comment by Salablefuzzball** [comment] 2020-01-03 14:27
Same. I can see the image element in dom but its size is 0x0 in spite of setting the size. The src is also the correct base64 string.

**Comment by kievmontana** [comment] 2020-03-30 10:54
Hi guys!

Make sure that you insert the Image in the correct way:
`<Image source={ {uri: 'YOUR IMAGE'} }/>`

Next check if your base64 size is not too large. - if the size is ok, it should work.

**Comment by luskin** [comment] 2020-07-30 02:11
@kievmontana can you provide a working example? when we use `uri` it's demanding that we also use `headers`, `body`, and `method` parameters as defined in the `SourceObject` interface

**Comment by kievmontana** [comment] 2020-07-31 08:24
@luskin Hey, it was quite long time ago and I can be wrong but if you receive API related errors as you mentioned, try to check the Headers on the back-end. We had similar issues with our AWS setup. Regarding the code, there is nothing special.

![Screenshot at Jul 31 11-22-28](https://user-images.githubusercontent.com/32641878/89015790-54013180-d320-11ea-95f4-411d30fe99c2.png)

**Comment by Devorein** [comment] 2021-09-01 15:46
Any update on this issue. Its still broken as of now.

**Comment by outpark** [comment] 2021-10-03 09:21
Same to me. Any solution to this? Basically it's not able to render on-the-fly base64 images when using PDFDownloadLink

**Comment by gabrielmilioli** [comment] 2021-11-12 03:03
I'm still having this issue.

None of this works:
`<Image source={{ uri: imageBase, method: 'GET', headers: [], body: '' }} />`
`<Image source={{ uri: imageBase }} />`
`<Image src={imageBase} />`

**Comment by diegomura** [comment] 2022-06-05 19:40
@gabrielmilioli that doesn't seem related to base64 images (which is what this issue is about). base64 images are working in latest versions. @kiranb555 in your case it probably doesn't work since `data:image/svg` arent supported. I'm going to close this since it's a pretty old ticket. Please submit any remaining problem as a new issue

**Closed by diegomura** 2022-06-05 19:40 UTC
