### ISSUE TITLE
Image component fails to render certain images, whereas the regular <img /> tag does render them

### ISSUE THREAD

**Issue by mubin86** [diegomura/react-pdf#2651] opened 2024-02-18 13:16 UTC
**Describe the bug**
We are encountering an issue with rendering images in our PDF documents. Specifically, `certain images` are consistently missing from the rendered PDF output, while others render perfectly without any problems. We have attempted to render the images using both the `Buffer and valid image URL` approaches as outlined in the documentation, but neither method has resolved the issue. Upon attempting to render the images, I saw that  it takes up a certain area in the PDF space, but it does not actually render that image. This behaviour is consistent across multiple attempts.

To debug the issue, I pasted the `Base64` containing the image into a React playground using a `regular <img /> tag`, and it appeared and functioned correctly. However, when I pasted the `same Base64 ` into the react-pdf playground https://react-pdf.org/repl, the image `failed to appear`. It's worth noting that the image size is only `3MB`, and there are `no CORS` issues to account for. Despite these observations, the image still does not render within the react-pdf playground.

Here I am attaching screenshot for your reference.
<img width="1512" alt="Screenshot 2024-02-18 at 5 17 08 PM" src="https://github.com/wojtekmaj/react-pdf/assets/52404512/32cb3c5a-2673-460d-8f96-72e8de27b762">
<img width="1436" alt="Screenshot 2024-02-18 at 5 29 29 PM" src="https://github.com/wojtekmaj/react-pdf/assets/52404512/a5112bb8-0254-400f-8ff5-6d8782d1d1df">

**To Reproduce**
To identify the issue, simply paste the Base64 from here https://drive.google.com/file/d/1lwIPXb7rIlQSB6Fqf-CbZ8DF7T7Wq45Z/view?usp=sharing within a regular `<img /> tag` in any React playground. Additionally, paste the `same Base64 ` in the  https://react-pdf.org/repl `react-pdf playground` using the custom `<Image /> component` from the library. This will allow you to easily visualize the problem.

**Desktop (please complete the following information):**

- OS: `MacOS 13.0`
- Browser `chrome`
- React-pdf version `3.3.8`

**Comment by krishna-404** [comment] 2024-02-18 18:33
Duplicate of #2639

**Comment by dmitryTurov** [comment] 2024-02-21 17:26
I suppose if an image has geolocation metadata attached [jay-peg](https://github.com/diegomura/jay-peg) fails to parse it. opened the related issue https://github.com/diegomura/jay-peg/issues/4

**Comment by dmitryTurov** [comment] 2024-02-22 17:34
as a workaround
`"resolutions": {
    "@react-pdf/image": "<2.3.2"
  }`
to use jpeg-exif instead of jay-peg

**Comment by nikischin** [comment] 2024-03-08 13:20
I am also facing this issue with any JPEG image in Safari under Mac OS X. Would be happy to see a fix soon, it seems like rendering PDFs client side isn't too reliable at all unfortunately :(

**Comment by PelosiTech** [comment] 2024-03-12 17:45
Add this

  "resolutions": {
    "@react-pdf/layout": "3.6.4",
    "@react-pdf/textkit": "4.3.0",
    "@react-pdf/image": "2.2.2",
    "@react-pdf/pdfkit": "3.1.2"
  }

Will fix a lot of issues for everyone.

**Closed** 2024-03-25 17:21 UTC

**Comment by mubin86** [comment] 2024-04-04 10:57
@diegomura Still facing this weird issue with the latest version [3.4.2](https://www.npmjs.com/package/@react-pdf/renderer/v/3.4.2). Its happening for a long time so would you mind taking a quick look into it?

**Comment by anantbansa1** [comment] 2024-05-04 23:09
> @diegomura Still facing this weird issue with the latest version [3.4.2](https://www.npmjs.com/package/@react-pdf/renderer/v/3.4.2). Its happening for a long time so would you mind taking a quick look into it?

I am also facing the same issue on version 3.4.4. did you find any solution

**Comment by jc-wow** [comment] 2024-06-02 14:47
yes, I encounted the same problem in version 2.5.0, I replaced Image component with normal img tag, it works!

**Comment by mubin86** [comment] 2024-06-15 07:22
### **Applied this small workaround(convert jpeg into png) to get rid of this issue and it works:**
   
     const resizeImage = (img: HTMLImageElement, maxWidth: number, maxHeight: number) => {
        const canvas = document.createElement('canvas');
        let width = img.width;
        let height = img.height;

        if (width > maxWidth) {
            height *= maxWidth / width;
            width = maxWidth;
        }

        if (height > maxHeight) {
            width *= maxHeight / height;
            height = maxHeight;
        }
  
        canvas.width = width;
        canvas.height = height;
        const ctx = canvas.getContext('2d');
        ctx.drawImage(img, 0, 0, width, height);

        return canvas;
     };           

     const maxWidth = 1000;
     const maxHeight = 800;
     const resizedCanvas = resizeImage(tempImage, maxWidth, maxHeight);

     // This is the converted png format
     const pngDataUrl = resizedCanvas.toDataURL('image/png', 0.8);

**Comment by coren-frankel** [comment] 2024-06-18 17:55
I am also still encountering this problem in version 3.4.2 and 3.4.4. So far, I haven't benefited from anyone's workarounds.

**Comment by nathanlao** [comment] 2024-09-19 21:03
> I suppose if an image has geolocation metadata attached [jay-peg](https://github.com/diegomura/jay-peg) fails to parse it. opened the related issue [diegomura/jay-peg#4](https://github.com/diegomura/jay-peg/issues/4)

For my case, removing the EXIF metadata helps solving this problem

**Comment by telisjok** [comment] 2024-09-20 22:14
> > I suppose if an image has geolocation metadata attached [jay-peg](https://github.com/diegomura/jay-peg) fails to parse it. opened the related issue [diegomura/jay-peg#4](https://github.com/diegomura/jay-peg/issues/4)
> 
> For my case, removing the EXIF metadata helps solving this problem

and how do you do that @nathanlao  ?

**Comment by Friendseeker** [comment] 2024-09-23 23:23
> > > I suppose if an image has geolocation metadata attached [jay-peg](https://github.com/diegomura/jay-peg) fails to parse it. opened the related issue [diegomura/jay-peg#4](https://github.com/diegomura/jay-peg/issues/4)
> > 
> > 
> > For my case, removing the EXIF metadata helps solving this problem
> 
> and how do you do that @nathanlao ?

I made patches to jay-peg and now react-pdf is able to render most of previously unrenderable images. Try add `"jay-peg": "^1.1.0"` to your `package.json` or bump your `"@react-pdf/renderer"` version to `4.0.0` and that should resolve the issue for most people.
