### ISSUE TITLE
Version doesn't support

### ISSUE THREAD

**Issue by Amyx000** [diegomura/react-pdf#2039] opened 2022-10-06 06:05 UTC
React 18.2.0 doesn't work with @react-pdf/renderer 3.0.0 ?

npm ERR! Found: react@18.2.0

<img width="295" alt="image" src="https://user-images.githubusercontent.com/104687128/194226639-72367a13-55c4-4584-ac8d-38eb1cf1d5b0.png">

**Comment by kalanchoej** [comment] 2022-10-06 18:57
We've also been running into this issue.

**Comment by chathu-novade** [comment] 2022-10-07 04:52
Duplicate of #2020 #1971 #1878 #1926

**Closed** 2022-10-27 05:39 UTC
