### ISSUE TITLE
Nested page break doesn't work

### ISSUE THREAD

**Issue by duyank** [diegomura/react-pdf#1510] opened 2021-09-17 09:05 UTC
**Describe the bug**
When I use break for nested View component. it doesn't work

**To Reproduce**
https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e619da74e5400a86146c00c9230580231500f4e3250e1d401a920c01ddd46ad3b74c0046009c30f00d6d80379473083005f039c02407b113a6cac004ccaaa6c1c86cada7aee9411c6eecabc02eaca740cccacec0400dc64640062e0500074967c48d018e678761c00663c8c480036009e005c3000e400f210ba3c4d00269d00341c10e6c01d9d00165050000e106d4a4ab58510457cd03c5048c045a08c4a104a207d03834a006ef200cc4a009a00faa200d29a006c20001c00ea206ba9800aa833ba319e000d00270f0008270a2bcd6a9d320b9b2b9001295980502e0d0f2251620d2a782a22150e82c1298818a00000

**Screenshots**
![image](https://user-images.githubusercontent.com/19285404/133756222-44ac11bd-8ef5-495a-afee-95c1d2a05565.png)

**Comment by asgerhallas** [comment] 2021-10-13 14:35
Is this a duplicate of https://github.com/diegomura/react-pdf/issues/1037?

**Closed** 2021-10-19 00:30 UTC
Labels: bug

**Comment by OliverLeighC** [comment] 2023-08-22 18:12
This is broken again in v3 https://github.com/diegomura/react-pdf/issues/1037#issuecomment-1688655756
