### ISSUE TITLE
Copy-paste issue for registered font

### ISSUE THREAD

**Issue by arathithamban** [diegomura/react-pdf#1950] opened 2022-07-22 09:18 UTC
**Describe the bug**
Copy-paste is not working correctly for the PDFs generated with the registered font.

**To Reproduce**
I was generating PDF files using react-pdf/renderer
Registered the font like this:
`  Font.register({
    family: 'Gelasio-Regular',
    src: __dirname + '/Gelasio-Regular.ttf'
  });`
But when copy-paste the content of the PDF file, it is not coming correctly.

Here is the generated PDF file:
[test.pdf](https://github.com/diegomura/react-pdf/files/9166399/test.pdf)

When copy-pasting the content, I am getting like this:
`Oce􀀄`
 
Downloaded the font Gelasio-Regular.ttf file from: [https://fonts.google.com/specimen/Gelasio](https://fonts.google.com/specimen/Gelasio)

**Other information**
 - React-pdf version: 2.1.1

**Comment by anthares-dev** [comment] 2022-09-13 08:37
Hi, same problem. Copying some words, the characters are changed. Same problem if trying to search the text within the pdf.

**Comment by chathu-novade** [comment] 2022-09-13 08:58
Which @react-pdf/renderer version are you using?

**Comment by anthares-dev** [comment] 2022-09-13 10:33
I'm using 2.0.21
The issue appears using fonts Nunito and OpenSans.

**Comment by chathu-novade** [comment] 2022-09-13 10:34
I'm using custom font Noto-Sans and see no issue with the latest version `3.0.0`

**Comment by ErnestMcBeard** [comment] 2022-09-20 21:42
+1 to seeing this issue generating a pdf. Using the Roboto font from Google. Tried upgrading to React-PDF 3.0.0 and got the latest version of the font

**Comment by anthares-dev** [comment] 2022-09-22 14:59
Issue can be reproduced with the following fonts:
**Nunito, Montserrat, NotoSans and Roboto**

No problem if using Raleway or JosefinSans

My React-PDF version is 2.1.0

**Comment by SongRongLee** [comment] 2022-11-28 12:46
I'm facing the same issue using [Google NotoSansTC Font](https://fonts.google.com/noto/specimen/Noto+Sans+TC?subset=chinese-traditional&noto.lang=zh_Hant&noto.script=Hant).
`@react-pdf/renderer` version: `3.0.0`
Both Chinese & non-Chinese characters are copied as wrong text.
I have tried the `birdfont` and `fontforge` workaround, but non of them works for me.
Importing & exporting the font using `fontforge` fixes part of the issue, most of the characters can be copied correctly, but some glyph cannot shown as usual anymore.

**Comment by chathu-novade** [comment] 2022-11-28 12:48
@SongRongLee What is the `fontforge` workaround?

**Comment by SongRongLee** [comment] 2022-11-28 12:53
@chathu-novade 
As described in [this reply](https://github.com/diegomura/react-pdf/issues/915#issuecomment-1090175507)

**Comment by jxbaker-sep** [comment] 2023-01-24 15:38
We're having this same issue with Google Outfit. We only have Latin characters in our pdf. Both copy-paste and search show the same errors, e.g. "specific" becomes "specixc". If we generate the PDF from a different source (Figma), it does not have this error. The fontforge fix did not work.

I can provide PDFs and/or example code if requested.

**Comment by justin-hackin** [comment] 2023-03-15 14:04
FYI, if this is more important than the appearance of your text, I would advise removing the custom font altogether as it seems to solve the issue. In my case, it was because I'm using this for a resume that is often consumed by algorithms.

**Comment by peilong-du** [comment] 2023-10-03 14:57
@victorfu Can you please share the rewritten method? I'm running into the same issue but I'm unfamiliar with pdf cmaps and encoding.

**Comment by victorfu** [comment] 2023-10-09 01:44
> @victorfu Can you please share the rewritten method? I'm running into the same issue but I'm unfamiliar with pdf cmaps and encoding.

@peilong-du check this pull request [https://github.com/diegomura/react-pdf/pull/2408](https://github.com/diegomura/react-pdf/pull/2408)

**Comment by peilong-du** [comment] 2023-10-09 13:43
Thanks @victorfu !!!

**Comment by irian-codes** [comment] 2023-10-18 19:28
> > @victorfu Can you please share the rewritten method? I'm running into the same issue but I'm unfamiliar with pdf cmaps and encoding.
> 
> @peilong-du check this pull request #2408

Thanks!!! I've been able to build and create a patch-package for this issue which is a lifesaver because I'm using it to build my resume and ATS software would read it wrong.

**Comment by sandeepdotcode** [comment] 2023-10-29 09:58
Do we have an ETA on when the next release is gonna be after the pull request is merged?

@irian-codes I'm using this in a resume builder that i use for my own resume. Can you share the patch-package you built?

**Closed** 2024-01-15 11:22 UTC

**Comment by EvgeniyBudaev** [comment] 2025-01-07 07:19
@react-pdf/renderer version 4.1.6 The problem is reproducible. https://github.com/diegomura/react-pdf/issues/3009

**Comment by VladSez** [comment] 2025-03-08 14:10
I also experience the same problems with registered fonts (Open Sans) as in #3009 

```
 "@react-pdf/layout": "4.4.0",
 "@react-pdf/renderer": "4.3.0",
```
