### ISSUE TITLE
Incompatible with Webpack 5 due to Buffer dependency

### ISSUE THREAD

**Issue by csvan** [diegomura/react-pdf#1029] opened 2020-10-14 06:35 UTC
Webpack 5 removes Buffer (see https://webpack.js.org/migrate/5/), effectively breaking this library since it has explicit usages of it in the code.

**Comment by gilberto1991** [comment] 2020-10-26 10:12
I also have this problem

**Comment by GregdTd** [comment] 2020-12-08 12:07
Same here, any news ?

**Comment by GregdTd** [comment] 2020-12-08 13:06
I was finally able to make it works.. 
`npm install assert browserify-zlib buffer process stream-browserify util`

Then in my webpack config:
```
const webpack = require('webpack');

module.exports = {
 {...}
    resolve: {
        alias: {
            process: 'process/browser',
            stream: "stream-browserify",
            zlib: "browserify-zlib"
        }
    },
    plugins: [
        new webpack.ProvidePlugin({
            process: 'process/browser',
            Buffer: ['buffer', 'Buffer'],
        }),
    ]
}
```

**Comment by matheusgrieger** [comment] 2020-12-19 03:31
@GregdTd that didn't work for me though...

**Comment by csvan** [comment] 2020-12-19 09:23
@matheusgrieger I solved it in the same way. What error are you getting? What if you add buffer under `resolve.fallback` as well or instead of `resolve.alias`?

**Comment by matheusgrieger** [comment] 2020-12-19 12:36
@csvan tried that but didn't work. Actually my error was being caused by a state update in another component while the PDF was rendering. Though it didn't change anything at all about the PDF content, it was crashing the app.

Some context would be good, too. I'm running React PDF in Electron and don't even need these fallbacks at all...

**Comment by mstrk** [comment] 2021-01-19 14:38
@matheusgrieger I also made it work with `resolve.fallback` but did not had to install `buffer` for example. and I think @GregdTd is missing some alias like `assert` and `util` that where installed.

I know that it's probably late and you already fixed it or move on, but if you have some error log to show us, then we could help you debug that.

**Comment by matheusgrieger** [comment] 2021-02-10 17:50
@mstrk I will happily get some logs to help you debug. But won't be possible for now though, as I have to change the way I wired up the app.

**Comment by osimuka** [comment] 2021-02-18 21:54
```

```
```Uncaught ReferenceError: Buffer is not defined
    at eval (DecodeStream.js:31)
    at Object.eval (DecodeStream.js:98)
    at eval (DecodeStream.js:102)
    at Object../node_modules/restructure/src/DecodeStream.js (bundle.js:9842)
    at __webpack_require__ (bundle.js:10651)
    at fn (bundle.js:10882)
    at Object.eval (EncodeStream.js:9)
    at eval (EncodeStream.js:151)
    at Object../node_modules/restructure/src/EncodeStream.js (bundle.js:9852)
    at __webpack_require__ (bundle.js:10651)
```

**Comment by osimuka** [comment] 2021-02-19 10:00
> I was finally able to make it works..
> `npm install assert browserify-zlib buffer process stream-browserify util`
> 
> Then in my webpack config:
> 
> ```
> const webpack = require('webpack');
> 
> module.exports = {
>  {...}
>     resolve: {
>         alias: {
>             process: 'process/browser',
>             stream: "stream-browserify",
>             zlib: "browserify-zlib"
>         }
>     },
>     plugins: [
>         new webpack.ProvidePlugin({
>             process: 'process/browser',
>             Buffer: ['buffer', 'Buffer'],
>         }),
>     ]
> }
> ```

After doing the above I get this error:

```
TypeError: Buffer.isBuffer is not a function
    at PDFDocument._write (pdfkit.browser.es.js:4190)
    at new PDFDocument (pdfkit.browser.es.js:4085)
    at Root._callee$ (react-pdf.browser.es.js:185)
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:293)
    at Generator.eval [as next] (runtime.js:118)
    at asyncGeneratorStep (asyncToGenerator.js:3)
    at _next (asyncToGenerator.js:25)
    at eval (asyncToGenerator.js:32)
```

**Comment by knoefel** [comment] 2021-02-19 11:17
@osimuka In my setup (nx monorepo) i also had to add the following line in `polyfills.ts`:

`(window as any)['global'] = window;`

I guess you can also add this line in your index.html in a `script` tag, if you don't have a polyfill file available.

**Comment by mstrk** [comment] 2021-02-19 12:48
@osimuka can you remove `process: 'process/browser',` line and uninstall buffer? also instead of using `alias` use `resolve.fallback`

something like this:
```js
{
 {...}
    resolve: {
        fallback: {
            util: require.resolve('util/'),
            assert: require.resolve('assert/'),
            stream: require.resolve('stream-browserify'),
            zlib: require.resolve('browserify-zlib'),
        },
    },
    plugins: [
        new webpack.ProvidePlugin({
             Buffer: ['buffer', 'Buffer'],
             process: 'process/browser',
        }),
    ],
}
```

hope it helps, cheers 🖖

**Comment by osimuka** [comment] 2021-02-19 12:51
> @osimuka In my setup (nx monorepo) i also had to add the following line in `polyfills.ts`:
> 
> `(window as any)['global'] = window;`
> 
> I guess you can also add this line in your index.html in a `script` tag, if you don't have a polyfill file available.

I'm using react17, with webpack5

I did this:
```
<script>
    var global = window;
  </script>
```

```
DecodeStream.js:32 Uncaught TypeError: Cannot read property 'prototype' of undefined
    at eval (DecodeStream.js:32)
    at Object.eval (DecodeStream.js:99)
    at eval (DecodeStream.js:103)
    at Object../node_modules/restructure/src/DecodeStream.js (bundle.js:9841)
    at __webpack_require__ (bundle.js:10681)
    at fn (bundle.js:10912)
    at Object.eval (Number.js:7)
    at eval (Number.js:106)
    at Object../node_modules/restructure/src/Number.js (bundle.js:9881)
    at __webpack_require__ (bundle.js:10681)
```

**Comment by osimuka** [comment] 2021-02-19 12:52
> @osimuka can you remove `process: 'process/browser',` line and uninstall buffer? also instead of using `alias` use `resolve.fallback`
> 
> something like this:
> 
> ```js
> {
>  {...}
>     resolve: {
>         fallback: {
>             util: require.resolve('util/'),
>             assert: require.resolve('assert/'),
>             stream: require.resolve('stream-browserify'),
>             zlib: require.resolve('browserify-zlib'),
>         },
>     },
>     plugins: [
>         new webpack.ProvidePlugin({
>              Buffer: ['buffer', 'Buffer'],
>              process: 'process/browser',
>         }),
>     ],
> }
> ```
> 
> hope it helps, cheers 🖖

I have tried that, I got
```
DecodeStream.js:32 Uncaught TypeError: Cannot read property 'prototype' of undefined
    at eval (DecodeStream.js:32)
    at Object.eval (DecodeStream.js:99)
    at eval (DecodeStream.js:103)
    at Object../node_modules/restructure/src/DecodeStream.js (bundle.js:9841)
    at __webpack_require__ (bundle.js:10681)
    at fn (bundle.js:10912)
    at Object.eval (Number.js:7)
    at eval (Number.js:106)
    at Object../node_modules/restructure/src/Number.js (bundle.js:9881)
    at __webpack_require__ (bundle.js:10681)
```

**Comment by mstrk** [comment] 2021-02-19 13:10
@osimuka did you remove this?
```html
<script>
    var global = window;
  </script>
```
and have `util`, `assert`, `stream-browserify`  and `process` installed right? just checking

I don’t  have `browserify-zlib` nor `buffer` installed. But you might try both variations.

I think you have a mismatch of libs installed for what some of your other packages expect. If you check this [line](https://github.com/foliojs/restructure/blob/master/src/DecodeStream.js#L6) on `DecodeStream.js` it expects a `buffer` object to work with, and this might not be the same object that is being passed.

**Comment by osimuka** [comment] 2021-02-19 14:45
> @osimuka did you remove this?
> 
> ```
> <script>
>     var global = window;
>   </script>
> ```
> 
> and have `util`, `assert`, `stream-browserify`, `browserify-zlib` and `process` installed right? just checking
> 
> I don’t have `buffer` installed. But you might try both variations.
> 
> I think you have a mismatch of libs installed for what some of your other packages expect. If you check this [line](https://github.com/foliojs/restructure/blob/master/src/DecodeStream.js#L6) on `DecodeStream.js` it expects a `buffer` object to work with, and this might not be the same object that is being passed.
> 
> EDIT: I do have `browserify-zlib` installed.

I have the modules ```util, assert, stream-browserify, browserify-zlib and process``` installed, however I have uninstalled buffer and I get the error 
```
If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "buffer": require.resolve("buffer/") }'
        - install 'buffer'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "buffer": false }
```
Once I install  buffer ```npm install buffer``` , it complies fine

I get this error on the browser with `Buffer: ['buffer', 'Buffer'],` removed
```
DecodeStream.js:31 Uncaught ReferenceError: Buffer is not defined
    at eval (DecodeStream.js:31)
```
Once I put it back, I get this error:
```
DecodeStream.js:32 Uncaught TypeError: Cannot read property 'prototype' of undefined
```

**Comment by mstrk** [comment] 2021-02-19 15:00
@osimuka do what webpack ask you to do. if you install buffer add it to fallback.

`add a fallback 'resolve.fallback: { "buffer": require.resolve("buffer/") }`

**Comment by osimuka** [comment] 2021-02-19 15:10
> @osimuka do what webpack ask you to do. if you install buffer add it to fallback.
> 
> `add a fallback 'resolve.fallback: { "buffer": require.resolve("buffer/") }`
> 
> and don't remove:
> 
> `Buffer: ['buffer', 'Buffer'],`

```./node_modules/restructure/src/Buffer.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
<path>/node_modules/restructure/src/Buffer.js
    Used by 53 module(s), i. e.
    <path>/node_modules/@react-pdf/renderer/dist/react-pdf.browser.es.js
<path>/node_modules/restructure/src/buffer.js
    Used by 12 module(s), i. e.
   <path>/node_modules/restructure/src/EncodeStream.js```

**Comment by mstrk** [comment] 2021-02-19 18:34
@osimuka hmmm, you have multiple modules defined.

I think you can’t define and fallback at the same time, I would have to search the docs in webpack. I would suggest you remove the `Buffer` key from `ProvidePlugin`, or change it to `buffer: 'buffer'`, but I have no idea. This will probably put you back at the point where you have mismatch modules from the consuming libs.

sorry for not being much help.

cheers🖖

**Comment by osimuka** [comment] 2021-02-20 12:33
> @osimuka hmmm, you have multiple modules defined.
> 
> I think you can’t define and fallback at the same time, I would have to search the docs in webpack. I would suggest you remove the `Buffer` key from `ProvidePlugin`, or change it to `buffer: 'buffer'`, but I have no idea. This will probably put you back at the point where you have mismatch modules from the consuming libs.
> 
> sorry for not being much help.
> 
> cheers🖖

Yah I tried that, but it gave the error `Buffer.isBuffer is not a function` 🤦 
Thanks for the help. I may have to revisit the library another time as I'm short for time to accomplish a new feature

**Comment by ECWireless** [comment] 2021-02-25 19:33
I'm getting the same error as initially mentioned, but still no luck after reading through all this. Would be awesome if this is continually looked into.

**Comment by gzhytar** [comment] 2021-02-26 17:18
This SE answer solved it for me: https://stackoverflow.com/a/65556946/15291780

**Comment by ECWireless** [comment] 2021-03-01 23:54
Hmm, still not working for me. I'm using snowpack, though, which may be why. Here is what my `snowpack.config.js` file looks like:
```
const NodePolyfillPlugin = require("node-polyfill-webpack-plugin")

// @ts-nocheck
/** @type {import("snowpack").SnowpackUserConfig } */
module.exports = {
  mount: {
    public: {url: '/', static: true},
    src: {url: '/dist'},
  },
  plugins: [
    '@snowpack/plugin-react-refresh',
    '@snowpack/plugin-dotenv',
    '@snowpack/plugin-typescript',
    [
      '@snowpack/plugin-webpack', {
        extendConfig: (config) => {
          config.plugins.push(new NodePolyfillPlugin());
          return config;
        }
      }
    ],
    ['snowpack-plugin-svgr', {
      htmlMinifierOptions: false, // disabled entirely,
    }]
  ],
...
```

And still getting the same error.

**Comment by gzhytar** [comment] 2021-03-02 12:14
@ECWireless, after I was experimenting with all the different modules and plugins, my 'node_modules' folder got bloated and random issues appeared.  What helped me is to delete 'node_modules'  and restore only needed packages from config. Maybe something that would help you as well.

**Comment by maxdev** [comment] 2021-04-07 21:31
> I was finally able to make it works..
> `npm install assert browserify-zlib buffer process stream-browserify util`
> 
> Then in my webpack config:
> 
> ```
> const webpack = require('webpack');
> 
> module.exports = {
>  {...}
>     resolve: {
>         alias: {
>             process: 'process/browser',
>             stream: "stream-browserify",
>             zlib: "browserify-zlib"
>         }
>     },
>     plugins: [
>         new webpack.ProvidePlugin({
>             process: 'process/browser',
>             Buffer: ['buffer', 'Buffer'],
>         }),
>     ]
> }
> ```

This solution actually works for me for Webpack 5.21.2

@diegomura  but I suppose it should be also fixed in version 2.0.0?

**Comment by GregdTd** [comment] 2021-05-04 13:39
Hello hello @diegomura,
FYI after upgrading to the `2.0.12` version today I got the following warning from webpack:
![image](https://user-images.githubusercontent.com/19348797/117011450-25204d80-acee-11eb-81fe-7204b4378e30.png)

Again I resolved it with:
```js
    resolve: {
        extensions: ['.js', '.jsx', '.json', '.ts', '.tsx'],
        plugins: [new TsconfigPathsPlugin()],
        alias: {
            process: 'process/browser',
            stream: "stream-browserify",
            zlib: "browserify-zlib",
            path: "path-browserify"
        },
        fallback: {
            fs: false,
            crypto: false //<----- adding this line removed the warning
        }
    },
```

**Comment by j0nezz** [comment] 2021-05-12 11:57
If anyone stumbles accross this using Next.js, you only need to add an alias for `stream` and `zlib` since Next.js already polyfills Buffer.

This config in next.config.js worked for me:
```
module.exports = {
 //...
webpack: (config) => {

    config.resolve.alias.stream = 'stream-browserify';
    config.resolve.alias.zlib = 'browserify-zlib';

    return config;
  },
}
```

**Comment by wasurocks** [comment] 2021-05-27 07:54
Thanks to all of you who have helped with the issue. For those of you using Gatsby, like me, it's not too difficult to configure webpack. Here are the steps to resolve the issue:

1. `yarn add` or `npm install` all of the following packages: `util stream-browserify path-browserify process buffer browserify-zlib assert`
2. Go to your `gatsby-node.js` folder, and add the following code:

`exports.onCreateWebpackConfig = ({ actions, plugins }) => {
    actions.setWebpackConfig({
        resolve: {
            alias: {
                stream: require.resolve('stream-browserify'),
                zlib: require.resolve('browserify-zlib'),
                path: require.resolve('path-browserify'),
            },
            fallback: {
                fs: false,
                crypto: false,
            },
        },
        plugins: [
            plugins.provide({
                process: 'process/browser',
                Buffer: ['buffer', 'Buffer'],
            }),
        ],
    });
};`

3. Restart the development process, maybe do a `gatsby clean` if you want, and you should be good to go!

References:
- This thread
- https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/#webpack-5-node-configuration-changed-nodefs-nodepath- (official gatsby v2 -> v3 docs)

**Comment by diegomura** [comment] 2021-06-05 22:27
Based on latest comments seems that fixes or workarounds have been found for many different types of app. Unfortunately, getting rid of `Buffer`, `stream` or `crypto` is not an option since some packages this lib rely on uses them extensively. I've made efforts on making them appear in less places as possible but not sure if will be even possible to make it work without shims. I'm going to close this for the moment. Can re-open if someone has an argument why should be that way 😄

**Closed by diegomura** 2021-06-05 22:27 UTC
Labels: bug

**Comment by mm-webx** [comment] 2021-07-23 09:58
> @osimuka can you remove `process: 'process/browser',` line and uninstall buffer? also instead of using `alias` use `resolve.fallback`
> 
> something like this:
> 
> ```js
> {
>  {...}
>     resolve: {
>         fallback: {
>             util: require.resolve('util/'),
>             assert: require.resolve('assert/'),
>             stream: require.resolve('stream-browserify'),
>             zlib: require.resolve('browserify-zlib'),
>         },
>     },
>     plugins: [
>         new webpack.ProvidePlugin({
>              Buffer: ['buffer', 'Buffer'],
>              process: 'process/browser',
>         }),
>     ],
> }
> ```
> 
> hope it helps, cheers 🖖

Sorry for offtopic, but maybe someone with same problem as me can look into this solution:
I had problem with `Buffer is not defined` and also with `Buffer.from is not a function`, because of webpack polyfills support.

**Comment by baonguyen2411** [comment] 2021-11-01 13:34
Hi all, I have the same issue with @osimuka when using webpack^5 and @react-pdf/renderer^2.0.20
I installed "npm install assert browserify-zlib buffer process stream-browserify util" and setup config webpack.
Hope someone can help me resolve this issue. Thanks all
![image](https://user-images.githubusercontent.com/27079028/139679877-2bb312c8-51de-402c-b00d-e0675c745181.png)

**Comment by joshlasdin** [comment] 2021-11-13 02:18
I also found that I was getting an error pretty much identical to @baonguyen2411 and was able to fix it by moving the codebase onto a case-sensitive partition. There's some weird case-sensitivity happening with Buffer/buffer and the restructure module

**Comment by baonguyen2411** [comment] 2021-11-13 09:09
Hi @joshlasdin, Can you help me explain more details or show me some examples?
Thanks @joshlasdin

**Comment by mohamedaliznidi** [comment] 2021-12-17 21:20
Hello i am havig the same problem 
ERROR  :
![error](https://user-images.githubusercontent.com/57480839/146608664-822d7ddf-737c-4884-8550-94efd78fd5f4.PNG)
  
`package.json`

```js
...
"dependencies": {
    "@react-pdf/renderer": "^2.0.21",
    "@testing-library/jest-dom": "^5.16.1",
    "@testing-library/react": "^12.1.2",
    "@testing-library/user-event": "^13.5.0",
    "assert": "^2.0.0",
    "brace": "^0.11.1",
    "browserify-zlib": "^0.2.0",
    "buffer": "^6.0.3",
    "pdfkit": "^0.13.0",
    "process": "^0.11.10",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "5.0.0",
    "readable-stream": "^3.6.0",
    "util": "^0.12.4",
    "web-vitals": "^2.1.2",
    "webpack-dev-server": "^4.6.0"
  },
...
```

`webpack.config.js`

```js
{
 {...}
    resolve: {
       alias: {
        fs: 'pdfkit/js/virtual-fs.js',
        'iconv-lite': false
      },
      fallback: {
        crypto: false,
        buffer: require.resolve('buffer/'),
        stream: require.resolve('readable-stream'),
        zlib: require.resolve('browserify-zlib'),
        util: require.resolve('util/'),
        assert: require.resolve('assert/')
      },
    },
    plugins: [
        new webpack.ProvidePlugin({
             Buffer: ['buffer', 'Buffer'],
             process: 'process/browser',
        }),
        new HtmlWebpackPlugin({
             template: path.resolve(__dirname, 'src/index.html'),
             inject: true
      }),
    ],
}

```

**Comment by jeetiss** [comment] 2021-12-18 08:03
@mohamedaliznidi I added webpack instructions, could you confirm that it works for you?

**Comment by baonguyen2411** [comment] 2021-12-18 14:40
Hi @jeetiss after I config look like this.
![image](https://user-images.githubusercontent.com/27079028/146644879-48774bae-afce-43a0-b4d0-b3e645601edb.png)
I still get the error, could you have me check?
![image](https://user-images.githubusercontent.com/27079028/146644898-9d7ff413-c226-4ef4-b1c1-7e4d993aeab6.png)
![image](https://user-images.githubusercontent.com/27079028/146644901-94aaeb21-b3c1-4544-9a36-5bf50eae449b.png)

**Comment by jeetiss** [comment] 2021-12-18 14:49
@baonguyen2411 why does your `restructure` package has two buffer files?
I have only one. try to remove `node-modules` and reinstall dependencies.


<img width="343" alt="Снимок экрана 2021-12-18 в 17 45 15" src="https://user-images.githubusercontent.com/6726016/146645129-ae5c6d28-ec01-42cc-bf78-da9789c6542d.png">

**Comment by baonguyen2411** [comment] 2021-12-18 15:53
Hi @jeetiss, I removed node_modules and install again but still get the same error
I have been checking the **restructure** folder but I don't see two buffer files :(
![image](https://user-images.githubusercontent.com/27079028/146647146-bdfb1055-e273-4481-ac14-79d4838f0a36.png)

**Comment by jeetiss** [comment] 2021-12-18 15:56
Are you using windows? I can't reproduce your problem

**Comment by baonguyen2411** [comment] 2021-12-19 08:51
Hi @jeetiss, yes I'm using windows :(

**Comment by jeetiss** [comment] 2021-12-19 14:45
I googled the issue text and found this https://stackoverflow.com/a/47632275

looks like the problem is not in webpack config

**Comment by mohamedaliznidi** [comment] 2021-12-19 20:39
hello @jeetiss i tryied to run my project with the exact config of the instruction but still having th same error ,

here is a link to the repo i used form my last test
[https://github.com/mohamedaliznidi/pdfReader-issue](url)

**Comment by violeta-cizikas** [comment] 2021-12-22 10:25
@j0nezz thank you! Greatly helped! : >

**Comment by bezchristo** [comment] 2022-01-01 18:24
I'm getting the same issue as @baonguyen2411.

```
Uncaught TypeError: Cannot read properties of undefined (reading 'prototype')
    at __extends (bundle.js:165215)
    at bundle.js:165231
    at Object.<anonymous> (bundle.js:165369)
    at Object../node_modules/@react-pdf/fontkit/node_modules/restructure/src/EncodeStream.js (bundle.js:165372)
    at Object.options.factory (bundle.js:504623)
    at __webpack_require__ (bundle.js:504038)
    at fn (bundle.js:504294)
    at Object.<anonymous> (bundle.js:164771)
    at Object../node_modules/@react-pdf/fontkit/node_modules/restructure/index.js (bundle.js:164797)
    at Object.options.factory (bundle.js:504623)
```

I have all the fallbacks setup but still getting this.

**Comment by aymanxdev** [comment] 2022-02-16 13:17
Can we find a way to fix this so it doesn't require modifying the webpack.config file?

**Comment by vtrphan** [comment] 2022-02-17 19:02
i also got the Buffer is not defined error despite having tried all of the recommended work arounds.... I'm using create-react-app v5. There must be a solution without requiring to modify the webpack config?

**Comment by wwww09z** [comment] 2022-02-25 00:35
> I'm getting the same issue as @baonguyen2411.
> 
> ```
> Uncaught TypeError: Cannot read properties of undefined (reading 'prototype')
>     at __extends (bundle.js:165215)
>     at bundle.js:165231
>     at Object.<anonymous> (bundle.js:165369)
>     at Object../node_modules/@react-pdf/fontkit/node_modules/restructure/src/EncodeStream.js (bundle.js:165372)
>     at Object.options.factory (bundle.js:504623)
>     at __webpack_require__ (bundle.js:504038)
>     at fn (bundle.js:504294)
>     at Object.<anonymous> (bundle.js:164771)
>     at Object../node_modules/@react-pdf/fontkit/node_modules/restructure/index.js (bundle.js:164797)
>     at Object.options.factory (bundle.js:504623)
> ```
> 
> I followed [these](https://github.com/diegomura/react-pdf#webpack-5) instructions and have all the fallbacks setup but still getting this.

Yes, I also got the exact same issue and cannot resolve it @jeetiss

**Comment by wwww09z** [comment] 2022-02-28 02:37
> @wwww09z @baonguyen2411 I'm assuming you are using Windows or MacOS in a non-case sensitive partition
> 
> You could try to add this rule to your webpack file
> 
> ```
> {
>   test: /restructure\/src\/[^w].js/,
>   use: [
>     {
>       loader: "imports-loader",
>       options: {
>         type: "commonjs",
>         imports: "multiple ../../buffer/ Buffer Buffer",
>       },
>     },
>   ],
> }
> ```
> 
> In my case (using NextJS 12), it looks like this ![image](https://user-images.githubusercontent.com/81442463/155766010-54724354-9bcd-4b3d-9d47-e168cd861fe0.png)
> 
> With that configuration you will force your restructure module to import the correct buffer from node_modules instead of trying to import a inner file of that library
> 
> EDIT:
> 
> If you don't already have it, you have to install `imports-loader` as a dev dependency, so webpack can use it as loader https://webpack.js.org/loaders/imports-loader/#getting-started

@Sasurtio  Thanks for your suggestion. Yes, im using macOS, but unfortunately, it still getting the same error after installing and configuring the `imports-loader`. So sad...

**Comment by Sasurtio** [comment] 2022-02-28 07:00
> @Sasurtio  Thanks for your suggestion. Yes, im using macOS, but unfortunately, it still getting the same error after installing and configuring the `imports-loader`. So sad...

Are you using `yarn` or another package manager?
Have you installed `buffer` library?

Could you provide your `webpack.config`?

**Comment by wwww09z** [comment] 2022-02-28 07:21
> > @Sasurtio  Thanks for your suggestion. Yes, im using macOS, but unfortunately, it still getting the same error after installing and configuring the `imports-loader`. So sad...
> 
> Are you using `yarn` or another package manager? Have you installed `buffer` library?
> 
> Could you provide your `webpack.config`?

Sure, yep, my project is using react and Im using `yarn` and have installed `buffer`.
My webpack.config.js is currently like this:
```
const webpack = require("webpack");

module.exports = {
  {...},
  plugins: [
    new webpack.ProvidePlugin({
      Buffer: ["buffer", "Buffer"],
      process: "process/browser",
    }),
  ],
  module: {
    rules: [
      {
        test: /restructure\/src\/[^w].js/,
        use: {
          loader: "imports-loader",
          options: {
            type: "commonjs",
            imports: "multiple ../../buffer/ Buffer buffer",
          },
        },
      },
    ],
  },
  resolve: {
    modules: ["src", "node_modules"],
    extensions: [".js"],
    fallback: {
      process: require.resolve("process/browser"),
      zlib: require.resolve("browserify-zlib"),
      stream: require.resolve("stream-browserify"),
      util: require.resolve("util"),
      buffer: require.resolve("buffer"),
      asset: require.resolve("assert"),
    },
  },
};
```

**Comment by wwww09z** [comment] 2022-03-01 22:21
Just for guys who have the same issue as mine and cannot resolve it after trying everything. I used the final solution which is to downgrade the Webpack from 5 to 4, then the issue resolved. This is not a solution actually, but just put here as an idea.

**Comment by yubinitdadev** [comment] 2022-03-03 07:13
@wwww09z which webpact version did you install? im trying to download my webpack but version 4.0.0 is stil giving me the error

**Comment by baonguyen2411** [comment] 2022-03-03 13:12
Hi @all, currently I have resolved the problem and I'm using Window, this is my Webpack 5 config
I hope it can help someone
![image](https://user-images.githubusercontent.com/27079028/156570880-1fa12497-cefb-41a1-b8b4-3c0a6b7f2ab7.png)

**Comment by yubinitdadev** [comment] 2022-03-03 13:32
@baonguyen2411 could you paste the code please >.< also what npm packages did you install for this? And is this webpack config or craco config?

**Comment by wwww09z** [comment] 2022-03-03 22:12
Hi @Sasurtio , thanks, if I still need to use webpack 5, I will try to create a mini repo later and let you know.

@yubinitdadev , here are the webpack and related packages' versions:
```
"webpack": "^4.43.0",
"webpack-cli": "^3.3.11",
"webpack-dev-server": "^3.11.0",
"webpack-manifest-plugin": "^4.0.2"
```

**Comment by Sasurtio** [comment] 2022-03-04 08:29
@wwww09z when you have time could you try this rule instead of the other?
After a test in another machine (a Mac with Big Sur installed) I realized that i had an error in the regex. I accidentally deleted a "+" sign after [^w], so it wasn't finding anything with more than 1 letter before the .js extension

Also added backslash routes support (windows without WSL will need it)

```
{
  test: /restructure(\/|\\)src(\/|\\)[\w]+.js/,
  use: [
    {
      loader: "imports-loader",
      options: {
        type: "commonjs",
        imports: "multiple ../../buffer/ Buffer Buffer",
      },
    },
  ],
}

```


Here is the regex test that demonstrates the effectivity of this regex file searching:

https://regex101.com/r/MZ7M1o/1

Let me know if it worked!

**Comment by luispolippo** [comment] 2022-03-05 01:40
Hi @Sasurtio. I have the exactly same problem that @wwww09z and i could solve with your help.
With the correct regex it works perfectly.
Thanks :smile:

**Comment by sohee-K** [comment] 2022-06-14 08:48
@Sasurtio Hi, I finally solved this issue that @baonguyen2411 first posed thanks to your code! Thanks a lot 😄

**Comment by kimberleyrogers** [comment] 2022-07-24 04:16
Agonised for hours but eventually found this guide which fixed it for me. I had an extra issues (browserify-zlib) but resolved it using the same principle (adding to config-overrides.js and installing)
[https://www.alchemy.com/blog/how-to-polyfill-node-core-modules-in-webpack-5]

**Comment by erwanriou** [comment] 2022-10-01 17:49
@WilliamPhilippe Yes for me as well

**Comment by NathanFirmo** [comment] 2023-03-23 16:26
> I was finally able to make it works.. `npm install assert browserify-zlib buffer process stream-browserify util`
> 
> Then in my webpack config:
> 
> ```
> const webpack = require('webpack');
> 
> module.exports = {
>  {...}
>     resolve: {
>         alias: {
>             process: 'process/browser',
>             stream: "stream-browserify",
>             zlib: "browserify-zlib"
>         }
>     },
>     plugins: [
>         new webpack.ProvidePlugin({
>             process: 'process/browser',
>             Buffer: ['buffer', 'Buffer'],
>         }),
>     ]
> }
> ```

For me, it works running this:

~~~bash
npm install assert buffer process stream-browserify util @react-pdf/zlib
~~~

and changing webpack config to:

~~~js
const webpack = require('webpack')

module.exports = {
    plugins: [
      new webpack.ProvidePlugin({
        Buffer: ['buffer', 'Buffer'],
      }),
      new webpack.ProvidePlugin({
        process: 'process/browser',
      }),
    ],
    resolve: {
      fallback: {
        zlib: require.resolve('@react-pdf/zlib'),
        stream: require.resolve('stream-browserify'),
        buffer: require.resolve('buffer'),
      },
    },
  }
~~~

**Comment by ijash** [comment] 2023-06-15 05:13
please re-open this thread as CRA now uses webpack 5 as the default install.
