### ISSUE TITLE
Cannot read property 'hyphenationFactor' of undefined

### ISSUE THREAD

**Issue by bkoltai** [diegomura/react-pdf#260] opened 2018-07-23 15:46 UTC
I am getting this exception when I have a `Text` component with text that is a single long word. I've made a simplified example of my use case [here](http://react-pdf.diegomura.com/repl?code=3187b0760ce02e004d09e01b02984605e18194a4e5600b6592803a6002764043299002806f00a0618023100137802e1859b36001da972e012cc0073002a2187f006c015800d2b21a3c54e90084414282002db2f59a458c932004880a12017b828d513f00cc16d805f0d6c50125028fc82420066ae58cec8fc004c002c014274001e5000828812d260fc00e4c0c860741405296c51a50062d42612887c300500f21000eeee5c059afe9ad400ae50040e619630d550314e7130008cf19530e959397985c5a5c8e5cb26d414d2520646a6fc89000c29fd6c1083ec412173e155d1b1fcf3001c7b0747f90b4b0994cea0d26a15da5d440f4fa2955b8c84307da1ca41f40422a63339bcd921355b6572ff02800ad06d009045e015206b8418d668156412132a000b4002553350c0bd3f0a499d46933c2648bf800d47641603b83e3e2108aa4f6470b94ad28585cae30cd110c43b78644deb3544fd916013b18cc307886a1178f5a12b6652a4234088318b5a4544a75c52a241400e50626762ea04136108020c1093810ad476040408861b209dfad2a628d134e29c2d9e6b5085011283f1f36c4734808c59829656c80cbe2362d074ed536c175ba0a1ee417b35be0025001b998cc1aab9485423b4076f44d0152b506104178007a65d4c20a4693416812603914ccb8832e2390ae32e006ef34f32e009a007d59001a5454a1027c00ea2073fb000aa5c4f098778001a002735099264a4118112a68c24cf51d2e0a74dd014303f483b0ea0240b0304c8098682600036a682f0c000112e1261917a822abb91603d4c8351e4560a6320302ba320c00c7322b010b40c0121a0ec150d4000d6718a06472c6c1913c531fc191b2010425fa8c7be8d220003090c1032000289a4c530841380d244cb24485c33164426bc5596444c3710864570b4350cc711089b0a4422644008e831728f3c0cc7cc17278325a1516f92e605c1704a1424171285173908ac5b27c5a5225cc5e6205a53145971505396e0cc5285f1a5c5400ba7d33075730587403036a5c0ec381e018008ab2c814172101441405a6460cc23083b14a7a749303b61422900311e82a1e8892ad646f84d7802d450200749d4a0dd630110a0690002212150c0299ff191bb4741b56dd87718c41da811d275d61f26dcd6c05c080c0375339b0000f19d00e0625140001f04c20c000a02bb1080a0e823028ea0a42703c2f830074fd708b0f7930083a2848c8074702e0a8e3070690f4fdd6f5a1be113c4c93b21d6b006368dd3f4fc96f4406a0c0f4e906d475d4fb1be0b36a73220f2e1cc64acf1320c2b5cc4b3ce4ca747c42c8b62c504cd4b4adb3f3315a0fcb9cd1b088ab9cd537806b9f5a4daf0bf4deb06cb3a6d08f107b72eab96d08d6c64b6cd37043b4eeeb343b5fac4bccdfb08a78def9b8af7baad07c83db5ac2c3acbb11f8b5d61b1edb089027bef1572d9314ec3c56309446efb308f4130825d02610b6e5b8685f618343303036ce93e4e536277668e51a4159b8f73b4f3be39ed6eec7feca793ff312c402cf57cde90f26f83ec5b05c086df50a41d70ddc1d9485d16095c1a49dfa0ddef76cc2f36d0ff008f57c4feaed3a1c2cf9c3fc4e3067e254dabfdfda271867bcfb1f62017dd973970e87ec20540b3688d052b3396e0d80243528b0c30b30364341aebc333a351c709448ef41feb000c24000)

**Comment by diegomura** [comment] 2018-07-23 16:30
just trace the error back, and should be fixed here: https://github.com/react-pdf/linebreaker/commit/baca9f798a86a555765887d0f71e9a6fd6a72ca2

Trying this later today, and releasing it in next version if everything worked ok. Thanks for the testing! It's really helpful for releasing a solid official `1.0.0` in some days

**Comment by diegomura** [comment] 2018-07-24 04:31
Fixed. You can see the REPL now.
The cause seemed to be that the linebreaker algorithm couldn't break this word, so the only way we have to show it is breaking in an arbitrary place based on char widths and available space.
I think it's better having this rather than not showing the line, not respecting the bounding box, and of course, throwing an error

**Closed by diegomura** 2018-07-24 04:31 UTC
