### ISSUE TITLE
I can't use renderToBuffer, renderToStream, etc ... in server side with NextJS 13+ with App router

### ISSUE THREAD

**Issue by mrkjofficial** [diegomura/react-pdf#2460] opened 2023-12-10 16:16 UTC
**Describe the bug**
In Next.js 13+ using App router , I'm unable to render PDF in Stream or Buffer in Next API routes 

**Error Message**
'ba.Component is not a constructor'

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Create a new Next.js porject select App Router during setup.
2. Add @react-pdf/renderer in the project.
3. Create a dummy PDF.
4. Try to render the PDF in the server side.

**Expected behavior**
App should run, react-pdf should render pdfs.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - React-pdf version v3.1.14

**Comment by jameschetwood** [comment] 2023-12-15 19:23
Try using the pages router instead. This worked for me.

**Comment by mrkjofficial** [comment] 2023-12-16 09:38
> Try using the pages router instead. This worked for me.

No solutions for app router yet? My whole application is based on the App router.

**Comment by Dru1DD** [comment] 2023-12-26 15:57
Unfortunetly, you can you @joshuajaco/react-pdf-renderer-bundled, but if you using packages like @david.kucsai/react-pdf-table you would have a problem, that it doesn't work with App Router. On Client component yeah, but in server component when you tried to use renderToBuffer - unfortunetly - not(

**Comment by bordeo** [comment] 2023-12-29 11:00
I think you should resolve using   `transpilePackages` as I mention [here](https://github.com/diegomura/react-pdf/issues/2350#issuecomment-1871950404)

**Comment by Dru1DD** [comment] 2023-12-29 14:45
You can create pages/api - route even in App Router and it works

**Comment by wojtekmaj** [comment] 2024-01-18 13:34
Duplicate of #2350

**Comment by airtonix** [comment] 2024-01-22 01:03
> You can create pages/api - route even in App Router and it works

That's fine if you want to create a server side endpoint for use at runtime, but remember that just because someone is using the `apps/*` directory, doesn't mean that they are running nextjs server side at runtime.

https://nextjs.org/docs/pages/building-your-application/deploying/static-exports

**Comment by diegomura** [comment] 2024-02-03 17:36
Closing it as duplicated

**Closed by diegomura** 2024-02-03 17:36 UTC
