### ISSUE TITLE
jpeg-exif: can't resolve 'fs'

### ISSUE THREAD

**Issue by arobert93** [diegomura/react-pdf#2535] opened 2024-01-20 19:15 UTC
**Describe the bug**

```
./node_modules/.pnpm/jpeg-exif@1.1.4/node_modules/jpeg-exif/lib/index.js:3:10
Module not found: Can't resolve 'fs'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/.pnpm/@react-pdf+pdfkit@3.1.1/node_modules/@react-pdf/pdfkit/lib/pdfkit.browser.js
./node_modules/.pnpm/@react-pdf+renderer@3.3.0_react@18.2.0/node_modules/@react-pdf/renderer/lib/react-pdf.browser.js
./src/components/core/pdf-viewer.tsx
```

**To Reproduce**

// page.tsx
```tsx
import * as React from 'react';

import { config } from '@/config';
import { PDFViewer } from '@/components/core/pdf-viewer';

export default function Page(): React.JSX.Element {
  return (
    <PDFViewer>
      {/* Document here */}
    </PDFViewer>
  );
}
```

/// pdf-viewer.tsx

```tsx
'use client';

import dynamic from 'next/dynamic';
import type ReactPDF from '@react-pdf/renderer';

export const PDFViewer = dynamic<ReactPDF.PDFViewerProps>(
  () => import('@react-pdf/renderer').then((m) => m.PDFViewer),
  {
    ssr: false,
    loading: () => null,
  }
);

```

**Expected behavior**
I expect it to not use any Node.js functions because if I remove the `use client` I get this error:

```
Error: PDFViewer is a web specific API. You're either using this component on Node, or your bundler is not loading react-pdf from the appropriate web build.
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: -
 - React-pdf version: v3.3.0

**Comment by genius-autos-admin** [comment] 2024-01-21 15:53
I have the same issue. It only started today. I'm also using "@react-pdf/renderer": "3.1.9"

**Comment by mcewball13** [comment] 2024-01-21 16:01
I have the same issue that also started today or just super recently. When I try to build, I get that error.

**Comment by mcewball13** [comment] 2024-01-21 16:28
Yeah, I was trying to track down the dep that was just recently updated to see if I could find it, but I couldn't find it. It says the issue is with `jpeg-exif`, but that package hasn't been updated in a million years.

> Everybody who's using this in Next.js app dir will have this issue because the bug was introduced in an internal dependency, not in the renderer package. Even downgrading isn't an option because it's a minor version and package managers will install automatically the latest minor (and patch) version of pdfkit.

**Comment by mcewball13** [comment] 2024-01-21 16:47
I copied the contents of my `yarn.lock` file from a commit where I could build. I found that `jpeg-exif` was introduced at some point in the versioning. My working build has no reference to `jpeg-exit` anywhere in the `yarn.lock` file at all. Here are some examples of the downgrade. 
![Screenshot 2024-01-21 at 11 36 52 AM](https://github.com/diegomura/react-pdf/assets/46138623/e537f9f2-315e-4fc5-91ff-294762e8d31a)
![Screenshot 2024-01-21 at 11 37 41 AM](https://github.com/diegomura/react-pdf/assets/46138623/aab40457-4c3b-44a8-a282-7623e431998d)
![Screenshot 2024-01-21 at 11 45 42 AM](https://github.com/diegomura/react-pdf/assets/46138623/0f39e0c5-bed7-4407-96b7-4cd9f8de8e33)

**Comment by airtonix** [comment] 2024-01-22 01:08
as a work around both yarn@4 and pnpm should be able to provide you a way to override the version of any transient dependancy you feel like you've no control over: 

- https://pnpm.io/package_json#pnpmoverrides
- https://yarnpkg.com/configuration/manifest#resolutions

**Comment by genius-autos-admin** [comment] 2024-01-22 05:39
i found that you can add craco to override the node modules and it works with both start and build. 

1. add craco using yarn add @craco/craco
2. add craco.config.js file into the root of your project.

module.exports = {
    webpack: {
        configure: (webpackConfig, { env, paths }) => {
            // Customize the webpack configuration here
            webpackConfig.resolve.fallback = {
                'fs': false,
                'os': false,
                'path': false,
            };
            return webpackConfig;
        },
    },
};

3. update your scripts in package.json file.

    "start": "NODE_OPTIONS='--max-old-space-size=4096' craco start",
    "build": "NODE_OPTIONS='--max-old-space-size=4096' craco build",
    "test": "craco test",
    "eject": "react-scripts eject",

4. Delete yarn lock and node modules.
5. yarn install
6. done

**Comment by Taofeeq-deru** [comment] 2024-01-22 22:06
I had the same issue, using just the webpack fallback without craco worked for me.

Just added this to my `nextConfig`

` webpack5: true,
  webpack: (config) => {
    config.resolve.fallback = { fs: false, os: false, path: false };

    return config;
  },`

**Comment by farreldarian** [comment] 2024-01-23 05:22
This is working for me

```
	"dependencies": {
		"@react-pdf/renderer": "^3.3.3",
	},
	"pnpm": {
		"overrides": {
			"@react-pdf/image": "2.2.3",
			"@react-pdf/pdfkit": "3.0.4"
		}
	},
```

**Comment by vasco3** [comment] 2024-01-23 06:13
This works for me as well! thanks
**Next.js v14.0.4**

> This is working for me
> 
> ```
> 	"dependencies": {
> 		"@react-pdf/renderer": "^3.3.3",
> 	},
> 	"pnpm": {
> 		"overrides": {
> 			"@react-pdf/image": "2.2.3",
> 			"@react-pdf/pdfkit": "3.0.4"
> 		}
> 	},
> ```

**Comment by Suduki** [comment] 2024-01-23 13:33
This seems to have been introduced in [https://github.com/diegomura/react-pdf/commit/a35b1ba18d293df51293600d8d56015094d222d8](https://github.com/diegomura/react-pdf/commit/a35b1ba18d293df51293600d8d56015094d222d8)

It would be great if you could revert it and not release it in a minor version in the future.

**Comment by farce1** [comment] 2024-01-23 14:11
if you are using yarn, you can use add to your package.json:

```
  "resolutions": {
    "@react-pdf/image": "2.2.3",
    "@react-pdf/pdfkit": "3.0.4"
  }
```

it should work as a workaround for the time being

**Comment by Kiborgik** [comment] 2024-01-23 18:26
for npm fix
```
"overrides": {
		"@react-pdf/image": "2.2.3",
		"@react-pdf/pdfkit": "3.0.4"
	},
```
but yes, we should wait a fix from author

**Comment by diegomura** [comment] 2024-01-23 23:37
Submitted a change in failing lib https://github.com/zhso/jpeg-exif/pull/36

Hopefully will be included soon, otherwise I might need to fork it or find another solution

**Comment by Kiborgik** [comment] 2024-01-24 01:59
> Submitted a change in failing lib [zhso/jpeg-exif#36](https://github.com/zhso/jpeg-exif/pull/36)
> 
> Hopefully will be included soon, otherwise I might need to fork it or find another solution

it has 2y ago last commit and owner has last commit at April, looks like create you own modern version of this will be better solution. Thank you for fast responding!

**Comment by ThomasRedstone** [comment] 2024-01-24 09:04
If jpeg-exif is stable there's absolutely no reason to be jumping to fork it right away.

The fact that it's had a total of 9 issues in its life, and this is one of them, suggests it's a tightly scoped package that does a good job (though it's only recently that the number of installs has jumped up!)

**Comment by diegomura** [comment] 2024-01-24 09:11
Agree @ThomasRedstone ! That lib does way more that what it's used for in here though. So if my PR does not get reviewed in time I might just port the only bit we need to pdfkit (both our fork and the original repo). Can't be halted forever. As said above I still want to give it a chance

**Comment by sebastiannoguera** [comment] 2024-01-24 18:18
any solve?

**Comment by felipehv** [comment] 2024-01-24 20:15
@diegomura no creo que sea buena idea que utilices una librería sin mantenimiento desde 2019, y con 12 estrellas en github, le bajas el nivel a esta tremenda librería que es react-pdf.
Lo más razonable en mi opinión es que hagas el fork o agregues el código que uses directamente dentro de la tuya, así no disminuyes la mantenibilidad de react-pdf.

Abrazo

**Comment by diegomura** [comment] 2024-01-25 00:24
@felipehv gracias por el feedback. Esta libreria la usa pdfkit desde hace ya un tiempo. Si quiero eventualmente usar el proyecto original (lo cual es deseable) tengo que lentamente solucionar las diferencias. El hecho de que no se mantenga desde el 2019 o mucho menos las estrellas que tenga no hace una libreria mejor o peor. En este caso lo importante es simplemente que utiliza una dependencia de Node que no vi al integrarlo

**Comment by satu-jovanhartono** [comment] 2024-01-30 04:49
up up

**Comment by datleviet** [comment] 2024-01-30 10:34
> This works for me as well! thanks **Next.js v14.0.4**
> 
> > This is working for me
> > ```
> > 	"dependencies": {
> > 		"@react-pdf/renderer": "^3.3.3",
> > 	},
> > 	"pnpm": {
> > 		"overrides": {
> > 			"@react-pdf/image": "2.2.3",
> > 			"@react-pdf/pdfkit": "3.0.4"
> > 		}
> > 	},
> > ```

I tried this workaround and it works fine in development mode, but I got this error when attempting to run `pnpm build`:
```
Attempted import error: 'Text' is not exported from '@react-pdf/renderer' (imported as 'Text').
```
(Likewise with other components I used: View, Page, Image, BlobProvider)
 
My dependencies: 
```
"next": "14.0.2",
"@react-pdf/renderer": "^3.3.3",
```

**Comment by kepope3** [comment] 2024-01-30 14:25
I'm using react-pdf in a library and using rollup to build it, all users of the library are facing the same error (Module not found: Error: Can't resolve 'fs'). I'm using rollup, any ideas if I can fix the issue? Can I add something in the rollup config?

Listed below:

import resolve from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import typescript from '@rollup/plugin-typescript';
import { terser } from 'rollup-plugin-terser';
import external from 'rollup-plugin-peer-deps-external';
import postcss from 'rollup-plugin-postcss';
import dts from 'rollup-plugin-dts';
import image from '@rollup/plugin-image';
import babel from '@rollup/plugin-babel';
import svgr from '@svgr/rollup';
import pkg from './package.json';
import copy from 'rollup-plugin-copy';
import url from '@rollup/plugin-url';
import json from '@rollup/plugin-json';

export default [
  {
    input: 'src/index-rollup.ts',
    external: ['@react-pdf/renderer', '@datapunt/matomo-tracker-js'],
    output: [
      {
        file: pkg.main,
        format: 'cjs',
        sourcemap: true,
        name: 'react-ts-lib'
      },
      {
        file: pkg.module,
        format: 'esm',
        sourcemap: true
      }
    ],
    plugins: [
      external(),
      resolve(),
      commonjs(),
      typescript({ tsconfig: './tsconfig.json' }),
      babel({
        exclude: [
          'node_modules/**',
          'node_modules/@datapunt/matomo-tracker-js/**'
        ],
        babelHelpers: 'bundled'
      }),
      image(),
      svgr({ icon: true }),
      postcss(),
      terser(),
      json(),
      url({
        limit: 150000,
        include: ['**/*.ttf', '**/*.woff', '**/*.woff2'],
        emitFiles: true
      }),
      copy({
        targets: [{ src: 'src/assets/*', dest: 'dist/esm/assets' }]
      })
    ]
  },
  {
    input: 'dist/esm/index-rollup.d.ts',
    output: [{ file: 'dist/index-rollup.d.ts', format: 'esm' }],
    external: [/\.css$/],
    plugins: [dts()]
  }
];

**Comment by chandanaswal18** [comment] 2024-01-30 17:47
Issue with exceljs after updating dependencies

I attempted to fix issue by updating dependencies in my project's package.json (we are using npm):
"overrides": {
  "@react-pdf/image": "2.2.3",
  "@react-pdf/pdfkit": "3.0.4"
}

However, after making these changes, I encountered a new problem with exceljs, resulting in the error: "Uncaught SyntaxError: Invalid or unexpected token (at exceljs.bundle).
This issue is critical as it affects our production build. Can someone please provide guidance or a fix for resolving this?

**Comment by SUBstylee** [comment] 2024-01-30 21:47
This works with yarn:
```json
"resolutions": {
    "@react-pdf/image": "2.2.3",
    "@react-pdf/pdfkit": "3.0.4",
    "@react-pdf/layout": "3.5.0"
  },
```

This may work for npm, however I have not personally tested it:
```json
"overrides": {
    "@react-pdf/image": "2.2.3",
    "@react-pdf/pdfkit": "3.0.4",
    "@react-pdf/layout": "3.5.0"
  },
```

**Comment by dharaneem** [comment] 2024-01-31 07:10
> for npm fix
> 
> ```
> "overrides": {
> 		"@react-pdf/image": "2.2.3",
> 		"@react-pdf/pdfkit": "3.0.4"
> 	},
> ```
> 
> but yes, we should wait a fix from author

Thanks, this is working in local , but fails in Azure CI pipeline, Any fix for it?

**Comment by viniciusDantasUnicamp** [comment] 2024-02-01 13:07
I tried overriding ```@react-pdf/image``` and ```@react-pdf/pdfkit```, but when I try to run yarn it says that the version is incompatible with the requested one. Is there anywhere I could find the compatible versions?

```
warning Resolution field "@react-pdf/pdfkit@3.0.4" is incompatible with requested version "@react-pdf/pdfkit@^3.1.2"
warning Resolution field "@react-pdf/image@2.2.3" is incompatible with requested version "@react-pdf/image@^2.3.1"
warning Resolution field "@react-pdf/pdfkit@3.0.4" is incompatible with requested version "@react-pdf/pdfkit@^3.1.2"
```

**Comment by klingat** [comment] 2024-02-02 18:23
+1 Experiencing the same issues. Using the resolutions partially works. Was working fine on version 3.1.12

**Closed** 2024-02-03 17:26 UTC
