### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'return')

### ISSUE THREAD

**Issue by Sogeman** [diegomura/react-pdf#2973] opened 2024-11-21 13:57 UTC
**Describe the bug**
Updating to Version 4.x results in Error TypeError: Cannot read properties of undefined (reading 'return') as soon as updateInstance runs in a useEffect. It worked perfectly on 3.4.5
I don't see anything in the 4.0.0 release that should cause this.

called like this
useEffect(
        () => {
            updateInstance(<ProductPdf />);
        },
        // eslint-disable-next-line react-hooks/exhaustive-deps
        [
            locale,
            title,
            widthLabel,
            selectedVariant,
            specifications,
            selectedUpgrade,
        ],
    );

**Expected behavior**
The Template is updated with the new data

**Desktop (please complete the following information):**

- OS: MacOS, Windows
- Browser: all
- React-pdf version 9.1.1 with react-pdf/renderer at anything over 3.4.5

**Comment by mathewcst** [comment] 2024-11-21 14:55
I'm facing the exact same issue. Love to know if there's a solution for it.

**Comment by 63r6o** [comment] 2024-11-21 17:54
I think this is a duplicate of https://github.com/diegomura/react-pdf/issues/2957

**Closed** 2024-11-26 00:34 UTC
