### ISSUE TITLE
Node-React-Webpack - throwing error on a page where used @react-pdf/renderer 

### ISSUE THREAD

**Issue by cssjodhpur** [diegomura/react-pdf#1327] opened 2021-05-23 12:13 UTC
**Throwing error on a page where used @react-pdf/renderer, actually i'm using @react-pdf/renderer in my node/react application with webpack config. all are working fine in local environment but it's showing error in production on the same page where i used it. i think something is missing in build. can you please help me ?**

**Error**
**Uncaught EvalError:** Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

**Comment by tobua** [comment] 2021-06-09 13:14
Looks like you need to add a `Content-Security-Policy` header to your server response to allow 'unsafe-eval`. Check out my comment on this Duplicate of #1336.

**Comment by diegomura** [comment] 2021-08-18 04:08
Thanks @tobua ! That should fix it

**Closed by diegomura** 2021-08-18 04:08 UTC
Labels: bug
