### ISSUE TITLE
Primitives is not defined with parcel 2 build command output

### ISSUE THREAD

**Issue by andrewvmail** [diegomura/react-pdf#1915] opened 2022-07-05 08:17 UTC
Using  @react-pdf/renderer 2.3.0" and latest parcel 2, production build, builds fine but opening the app you will see 
<img width="478" alt="image" src="https://user-images.githubusercontent.com/2431354/177281424-dfe521da-e279-4bf1-854b-14310d9b1b94.png">

The reference error leads to primitives in the source map.
 
Minimal reproduction 
https://github.com/andrewvmail/parcel-react-pdf-bug-demo

```
git clone https://github.com/andrewvmail/parcel-react-pdf-bug-demo
cd parcel-react-pdf-bug-demo
yarn
parcel build src/index.html
cd dist
npx http-server 
# open localhost:8080

# another terminal
parcel serve src/index.html
# no console error
```

Thanks in advance!

**Comment by carlobeltrame** [comment] 2022-07-06 09:05
Sounds like a duplicate of #1317. The issues with ESM compatibility are deeper than just the default exports. @andrewvmail please join us at #1891 where we attempt to fix the browser and ESM compatibility, and discuss how the library will further develop in order to become isomorphic. It would help out greatly if you could test #1891 using parcel!

**Comment by andrewvmail** [comment] 2022-07-06 09:14
> I can not reproduce the problem, it's working!
> 
> Which version of parcel do you use?
> 
> <img alt="Снимок экрана 2022-07-06 в 12 02 37" width="1512" src="https://user-images.githubusercontent.com/6726016/177513139-f2c2ffaa-d13a-4bf7-930c-cedc56bc72f9.png">

parcel 2 latest as of yesterday

> I can not reproduce the problem, it's working!
> 
> Which version of parcel do you use?
> 
> <img alt="Снимок экрана 2022-07-06 в 12 02 37" width="1512" src="https://user-images.githubusercontent.com/6726016/177513139-f2c2ffaa-d13a-4bf7-930c-cedc56bc72f9.png">

I'm using parcel 2.5 globally installed, did you do parcel build or parcel serve? parcel serve works fine.
Have to clean it again and retry if you used parcel serve once.
```
rm -rf .parcel-cache
rm -rf dist
parcel build src/index.html
cd dist; npx http-server 
```

**Comment by andrewvmail** [comment] 2022-07-06 09:38
Just tried again using parcel 2.6.2. Parcel build still produces error. Identical problem to this one too https://github.com/diegomura/react-pdf/issues/1786

**Comment by tarabishy2020** [comment] 2022-07-08 14:51
"parcel": "^2.6.2",
"@react-pdf/renderer": "^2.3.0",
and getting similar error pointing to the last line
```
ReferenceError: $d3857507522fe20e$import$5ace8e5c686fb130 is not defined
```
```
var $d3857507522fe20e$export$2e2bcd8739ae039 = {
    pdf: $d3857507522fe20e$export$278e8ca9e1fa9094,
    Font: $d3857507522fe20e$export$89abf52a030e56ee,
    version: $d3857507522fe20e$export$83d89fbfd8236492,
    StyleSheet: $d3857507522fe20e$export$9d753cd7ae895cce,
    usePDF: $d3857507522fe20e$export$398b9fbd663a6614,
    PDFViewer: $d3857507522fe20e$export$e86b8823e5baa9d,
    BlobProvider: $d3857507522fe20e$export$5fb2f8b440914d36,
    PDFDownloadLink: $d3857507522fe20e$export$3b449de3ec3c756d,
    renderToStream: $d3857507522fe20e$export$97f86213fef5749d,
    renderToString: $d3857507522fe20e$export$80e7718417253a51,
    renderToFile: $d3857507522fe20e$export$138b5c407a9e1fda,
    render: $d3857507522fe20e$export$b3890eb0ae9dca99,
    //->>// ...$d3857507522fe20e$import$5ace8e5c686fb130
};
```

**Comment by andrewvmail** [comment] 2022-07-08 20:41
Here is a hot fix until parcel gets updated. https://gist.github.com/andrewvmail/a94a5a3671a8f58300c3163d07042686

**Closed** 2022-07-11 02:29 UTC

**Comment by yoonwaiyan** [comment] 2024-03-20 13:02
Is this fixed? I'm seeing the same error here in my project. My react version is 16.14.0, using Parcel 2.12.0, nodejs 16.20.2.
