### ISSUE TITLE
Page wrap with long Text does not allow to wrap it to more than 2 pages

### ISSUE THREAD

**Issue by kneczaj** [diegomura/react-pdf#1052] opened 2020-11-05 14:25 UTC
**Describe the bug**
There is an example attached. When `<Text>` contains a long text, and is placed inside `<Page wrap={true}>`, it can be displayed maximally on two pages. When it is longer it gets cut 

**To Reproduce**
1. Checkout the branch of this pull request https://github.com/diegomura/react-pdf/pull/1051
2. Run `yarn example multiPageWrap`
3. See that the generated pdf is cut and there is no `THE END` text at the end of the document.

_You can make use of [react-pdf REPL](https://react-pdf/repl) to share the snippet_

**Expected behavior**
The text should be fully rendered, probably on 3 pages.

**Screenshots**
<img width="993" alt="Zrzut ekranu 2020-11-5 o 15 22 09" src="https://user-images.githubusercontent.com/4245137/98252860-afc00400-1f7a-11eb-8a5d-edf158564e1d.png">
<img width="903" alt="Zrzut ekranu 2020-11-5 o 15 23 15" src="https://user-images.githubusercontent.com/4245137/98252998-d5e5a400-1f7a-11eb-99a2-62fe45c081da.png">

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7
 - Browser: node, chrome, safari
 - React-pdf version master branch, also latest at npm, see the pull request

**Comment by kneczaj** [comment] 2020-11-25 23:26
There were some formatting issues so the mentioned components were not visible in the description. The description is edited and fine now.

**Comment by diegomura** [comment] 2021-04-03 20:14
Just tested both v1 and v2 and couldn't reproduced it. Bth had changes about how pagination works so maybe it was fixed in those changes.

**Closed by diegomura** 2021-04-03 20:14 UTC
