### ISSUE TITLE
image example is broken

### ISSUE THREAD

**Issue by cookie-header** [diegomura/react-pdf#576] opened 2019-04-19 20:45 UTC
**Describe the bug**
https://react-pdf.org/repl?example=images
the image is not loaded in the example

**Comment by DavidMich1** [comment] 2019-05-14 17:27
I can confirm that it works on Chrome.

**Comment by samuraijane** [comment] 2019-08-08 12:35
The image example works in Chrome, Firefox, and Safari on desktop. It also works in mobile Safari. I am not able to check IE. @diegomura, you may want to close this issue.

**Comment by diegomura** [comment] 2020-07-21 04:52
Works for me too!

**Closed by diegomura** 2020-07-21 04:52 UTC
