### ISSUE TITLE
Could not locate module ./src/EncodeStream during jest tests

### ISSUE THREAD

**Issue by thayes-amplify** [diegomura/react-pdf#902] opened 2020-05-13 16:51 UTC
**Describe the bug**
Running unit tests against components that ultimately render a component that imports @react-pdf/renderer throws this error:

```
    Configuration error:
    
    Could not locate module ./src/EncodeStream mapped as:
    /[path to project]/src//EncodeStream.
    
    Please check your configuration for these entries:
    {
      "moduleNameMapper": {
        "/src(?!.*src)(.*)$/": "/Users/thayes/workspace/aqua-dashboard/src/$1"
      },
      "resolver": null
    }
```

I have pinpointed that this error was introduced once `@react-pdf/renderer` was installed and imported into a descendent component of an existing component that is covered by unit tests.

The only occurrences of `EncodeStream` I see in `node_modules/@react-pdf` are in the js files under `/fontkit/dist/`, but they don't import EncodeStream, but rather import `restructure` as `r` and call `r.EncodeStream()`.  So, I have no idea why it's trying to resolve a module named EncodeStream.  Running the app is fine, it's only when running tests with jest.

**Expected behavior**
Unit tests should not crash for components that import @react-pdf/renderer.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Browser: N/A
 - React-pdf version: 1.6.8

**Comment by PerraiD** [comment] 2020-11-18 14:28
Hi, did you find a solution ? 
i have the same problem but not only in my test but in my app to 

```javascript
import React from 'react';
import {
  Document, StyleSheet, Page, View, Image, Text,
} from '@react-pdf/renderer';
import PropType from 'prop-types';


// Create styles
const styles = StyleSheet.create({
  page: {
    flexDirection: 'row',
    backgroundColor: '#E4E4E4',
  },
  section: {
    margin: 10,
    padding: 10,
    flexGrow: 1,
  },
});

function Pdf({ image, placeName }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.section}>
          <Image
            style={styles.image}
            src={image}
          />
          <Text style={styles.subtitle}>
            {placeName}
          </Text>
        </View>
      </Page>
    </Document>
  );
}

Pdf.propType = {
  image: PropType.string.isRequired,
  placeName: PropType.string.isRequired,
};

export default Pdf;
```

**Comment by Krzyku** [comment] 2020-12-17 16:54
I had the same issue. The problem is in `moduleNameMapper`
Value `src/(.*)": "<rootDir>/src/$1"` means that every import matching `src/(.*)` should be resolved in `<rootDir>/src/$1`
One library uses the following import `./src/EncodeStream` so Jest tries to find this module in Your src directory.
In my case fix was simple - just have to add `^` at the beginning. In the @thayes-amplify code, this should work:
`"^/src(?!.*src)(.*)$/": "/Users/thayes/workspace/aqua-dashboard/src/$1"`

By the way - Your configuration will work only on Your computer because of the absolute path ;)

**Comment by diegomura** [comment] 2021-04-08 03:56
Seems like it's fixed. Thanks @Krzyku

**Closed by diegomura** 2021-04-08 03:56 UTC
