### ISSUE TITLE
JPG not showing on downloaded PDF. PNG works.

### ISSUE THREAD

**Issue by jackdewan** [diegomura/react-pdf#2662] opened 2024-02-29 00:15 UTC
Bug is in the repl. First image does not show(jpg) after downloading or printing. Second image shows(png) after downloading and printing.

**Comment by Penguinlay** [comment] 2024-03-04 18:40
Duplicate of https://github.com/diegomura/react-pdf/issues/2656

**Comment by kidusnegesse** [comment] 2024-03-27 18:04
What's the solution for this?

**Comment by diegomura** [comment] 2024-03-28 09:32
Should be solved by latest JPEG fix

**Closed by diegomura** 2024-03-28 09:32 UTC
