### ISSUE TITLE
I have also got this issue 279.4 ERROR in ./node_modules/yoga-layout/src/generated/YGEnums.ts 10:7 279.4 Module parse failed: Unexpected token (10:7) 279.4 You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders 279.4 | // @generated by enums.py

### ISSUE THREAD

**Issue by gaphel1** [diegomura/react-pdf#2508] opened 2024-01-18 11:38 UTC
**Describe the bug**
I have also got this issue 279.4 ERROR in ./node_modules/yoga-layout/src/generated/YGEnums.ts 10:7
279.4 Module parse failed: Unexpected token (10:7)
279.4 You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
279.4 | // @generated by enums.py

**Desktop (please complete the following information):**
 - OS: [ MacOS M3]
 - "@react-pdf/renderer": "^3.1.14",
 - "react-pdf": "^7.1.2",
It was working fine till 3 days back. We are using it for project now we are unable deploy from docker image. Any suggestion is very much appreciated

**Comment by wojtekmaj** [comment] 2024-01-18 11:56
Duplicate of #2499

**Comment by gaphel1** [comment] 2024-01-18 14:12
> Duplicate of #2499

Thank for the suggestion. It worked for us by installing @react-pdf/layout": "3.6.3", cause the error is caused it is not able to find the YGEnums.ts

**Closed** 2024-01-18 14:12 UTC

**Comment by wojtekmaj** [comment] 2024-01-18 14:45
It's the opposite. See my explanation in the original ticket.
