### ISSUE TITLE
Jpq/jpeg file couldn't render except .png

### ISSUE THREAD

**Issue by zcmgyu** [diegomura/react-pdf#379] opened 2018-11-19 08:46 UTC
**OS:**
macOS Mojave 10.14 (18A391)

**React-pdf version:**

> "@react-pdf/renderer": "^1.0.0-alpha.25",
> "react": "^16.5.2",

**Description:**
jpq/jpeg file hasn't been rendered when I used Image component. Png file works for me.

**How to replicate issue including code snippet (if applies):**
https://codesandbox.io/s/nnw62prrz4

**Comment by diegomura** [comment] 2018-12-12 18:18
Hey @zcmgyu . I suspect this might be an issue about how the lib works on codesandbox. Could you replicate this issue on an own node or web project? I've been testing jpg and png images and all seems to work

**Comment by zcmgyu** [comment] 2018-12-17 17:15
@diegomura Thanks you. I will try implementing on this weekend.

**Comment by diegomura** [comment] 2019-01-14 04:48
JPG images are being rendered correctly. I still asume this is caused by how this library runs on codesandbox. Closing this, unless until further details this is not the case 😄

**Closed by diegomura** 2019-01-14 04:48 UTC
