### ISSUE TITLE
web-pack 5 incompatible issue in react scripts 5.0.0 (CRA) without craco

### ISSUE THREAD

**Issue by Gopisuresh-Akula** [diegomura/react-pdf#1744] opened 2022-03-09 16:46 UTC
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
- install 'stream-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "stream": false }

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "zlib": require.resolve("browserify-zlib") }'
- install 'browserify-zlib'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "zlib": false }

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "zlib": require.resolve("browserify-zlib") }'
- install 'browserify-zlib'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "zlib": false }

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
- install 'stream-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "stream": false }

**I'm getting this issue while I'm using CRA react scripts 5.0.0 please check this issue**

**Comment by straycatse** [comment] 2022-03-10 17:54
Same here. I would like to find a solution without having to eject the CRA-project.

**Comment by diarcastro** [comment] 2022-03-11 20:45
I use this solution and I worked!
https://github.com/diegomura/react-pdf/issues/1740#issuecomment-1065509181

**Comment by Gopisuresh-Akula** [comment] 2022-03-12 03:21
@diarcastro thanks for ur response moreover it should be without craco setup do you have any solution ??

**Comment by Jaseibert** [comment] 2022-04-07 00:29
Still having the issue.

**Comment by inouekun** [comment] 2022-04-27 07:20
I use `patch-package` to edit/update the `node-modules/react-scripts/config/webpack.config.js` without having to eject the CRA. And then follow the https://github.com/diegomura/react-pdf#webpack-5

**Comment by johnnyb** [comment] 2022-05-04 20:30
For me, the only way I got it to work was to add the following to index.js:
```
import "process";
window.process = process;
```

**Comment by Qurishe** [comment] 2022-05-27 14:10
@inouekun it has been 2 days since i am struggling with this problem, can you please share your modified version of webpack.config.js.
i just don't know where to put these config files inside of the webpack.config.js file.
it would be a great help.
thanks again for the help

**Comment by oregev** [comment] 2022-05-31 19:47
Can this help?
will handle WP5 with CRA 17-18
https://www.npmjs.com/package/react-pdf-browser

**Comment by oregev** [comment] 2022-05-31 20:10
@Qurishe 
Yes ...
But you import from this package.
i.e `import { what you need } from 'react-pdf-browser'`

**Comment by Qurishe** [comment] 2022-05-31 20:13
@oregev that's was exactly the answer to my question i will try it out and will let u know....
Thank you again😊😊

**Comment by diegomura** [comment] 2022-05-31 21:46
Why creating two issues about the same? https://github.com/diegomura/react-pdf/issues/1740

**Comment by diegomura** [comment] 2022-06-04 08:05
Closing as duplicate of this https://github.com/diegomura/react-pdf/issues/1795

**Closed by diegomura** 2022-06-04 08:05 UTC

**Comment by adamduncan** [comment] 2022-06-15 13:05
Have added an explanation (following on from @inouekun's pointer) on how we got this one working in the main issue ticket: https://github.com/diegomura/react-pdf/issues/1740#issuecomment-1156446445

**Comment by Gopisuresh-Akula** [comment] 2022-06-23 05:38
production mode not getting issue like  
[Could not load content for webpack://react-pdf @react-pdf/renderer/lib/react-pdf.browser.es.js.map: Fetch through target failed: Unsupported URL scheme; Fallback: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME](https://www.google.com/search?rlz=1C1ONGR_enIN1004IN1004&q=Could+not+load+content+for+webpack://react-pdf+@react-pdf/renderer/lib/react-pdf.browser.es.js.map:+Fetch+through+target+failed:+Unsupported+URL+scheme;+Fallback:+HTTP+error:+status+code+404,+net::ERR_UNKNOWN_URL_SCHEME&spell=1&sa=X&ved=2ahUKEwj6kt_76sL4AhXXT2wGHYSjC4EQkeECKAB6BAgBEDM&cshid=1655961964001777)

@oregev pls check out these

**Comment by RiJung** [comment] 2022-07-17 16:28
still facing these issue

if someone need i use react rewrite

in package.json
```
 "start": "cross-env PORT=3000 react-app-rewired start"
```

in config-overrides.js

```
const webpack = require('webpack'); 
module.exports = function override(config) { 
		const fallback = config.resolve.fallback || {}; 
		Object.assign(fallback, { 
                process: require.resolve("process/browser"),
                zlib: require.resolve("browserify-zlib"),
                stream: require.resolve("stream-browserify"),
                util: require.resolve("util"),
                buffer: require.resolve("buffer"),
                asset: require.resolve("assert"),
                fs: require.resolve('browserify-fs')
      }) 
   config.resolve.fallback = fallback; 
   config.plugins = (config.plugins || []).concat([ 
   	new webpack.ProvidePlugin({ 
        Buffer: ['buffer', 'Buffer'],
    	process: 'process/browser'
    }) 
   ]) 
   return config; }
```

**Comment by paul0rocha** [comment] 2023-05-19 00:14
Error: Module not found: Error: Can't resolve 'fs' in 'C:\Users\paulo\Downloads\aula13\aula13\aula13-front\node_modules\send\node_modules\mime'
