### ISSUE TITLE
Error: Cannot find module './zlib_bindings'

### ISSUE THREAD

**Issue by Mohammed-Qasim93** [diegomura/react-pdf#1678] opened 2022-01-14 11:23 UTC
### hi guys
I have an error with my app it says

**Error: Cannot find module './zlib_bindings'**

### my webpack config 

<img src="https://f.top4top.io/p_2205ndy6s1.png" />

**Comment by nischalp444** [comment] 2022-01-21 10:00
I am having the same issue

**Comment by jeetiss** [comment] 2022-01-21 10:08
Could you please provide more information about setup and error or create repo with minimal reproduction because this info is limited and I don't know how to help you?

**Comment by nischalp444** [comment] 2022-01-21 15:56
Yes, I will list the steps that I took to get to the issue that I am facing.

1.  Create a React Project
2.  yarn add @react-pdf/renderer

issues: 
    - Module not found: Error: Can't resolve 'stream' in 'react- 
      pdf\node_modules\@react-pdf\pdfkit\lib'
    - Module not found: Error: Can't resolve 'zlib' in 'react- 
      pdf\node_modules\@react-pdf\pdfkit\lib'
    - Module not found: Error: Can't resolve 'zlib' in 'react- 
      pdf\node_modules\@react-pdf\png-js\lib'
    - Module not found: Error: Can't resolve 'stream' in 'react- 
    pdf\node_modules\blob-stream'
    - Module not found: Error: Can't resolve 'stream' in 'react- 
    pdf\node_modules\restructure\src'

3. In order to fix these issues I tried doing the "yarn add process browserify-zlib stream-browserify util buffer assert", but the issues were still there.
4. That was unsuccessful so I tried to add the following code to webpack.config located inside node_modules/react-scripts.

```
const webpack = require("webpack");

module.exports = {
  /* ... */

  resolve: {
    fallback: {
      process: require.resolve("process/browser"),
      zlib: require.resolve("browserify-zlib"),
      stream: require.resolve("stream-browserify"),
      util: require.resolve("util"),
      buffer: require.resolve("buffer"),
      asset: require.resolve("assert"),
    }
  },
  plugins: [
    new webpack.ProvidePlugin({
      Buffer: ["buffer", "Buffer"],
      process: "process/browser",
    }),
  ]

  /* ... */
}
```

5. I went through the whole folder and made sure the placement was correct, but when I restarted the project it gave me a webpack error and I was unable to do a yarn start so I removed the changes that I made.
6.  I went installed each error that I was receiving with the folling code:
     
`npm i stream`
`npm i zlib`
`npm i stream`
     
7. this removed all the errors but the one that says "Error: Cannot find module './zlib_bindings"
8. I tried attaching the file to the webpack again, but I am getting the same error.


Please let me know if you need more information.

**Comment by brandonryan** [comment] 2022-01-21 17:39
This is an issue with the latest version of create react app (and really esm) requiring file extensions for all import paths.

**Comment by nischalp444** [comment] 2022-01-22 10:12
I was able to get it to work by using an older version

**Comment by jeetiss** [comment] 2022-01-22 12:47
> That was unsuccessful so I tried to add the following code to webpack.config located inside node_modules/react-script

I think this is the reason. CRA doesn't provide a way to modify webpack config. You have to run `inject` or use some other tools that patch it for you.

here is grate guide on how to use react-pdf with CRA and `craco` tool
https://dev.to/przpiw/react-pdf-rendering-4g7b

**Comment by brandonryan** [comment] 2022-01-24 07:38
I really don't think that makes sense... if its a library meant to be used in the browser, why does it depend on node libraries?

**Comment by nischalp444** [comment] 2022-01-25 19:35
I used the steps given from https://dev.to/przpiw/react-pdf-rendering-4g7b and it also worked. Thank you!

**Comment by Azamat-Shogen** [comment] 2022-05-07 22:25
> I used the steps given from https://dev.to/przpiw/react-pdf-rendering-4g7b and it also worked. Thank you!
thank you sir , worked for me as well

**Comment by CramerJ1470** [comment] 2022-05-17 03:21
i just renamed zlib/lib/zlib.js to zlib/lib/zlib_bindings.js and removed the code in the file

**Comment by CramerJ1470** [comment] 2022-05-17 03:22
dont need the polyfill...i just renamed zlib/lib/zlib.js to zlib/lib/zlib_bindings.js and removed the code in the file

**Comment by Beej126** [comment] 2022-05-25 20:20
bare min working online sample in case helps anybody: https://stackblitz.com/edit/react-pdf-demo2?file=src%2Findex.js

**Comment by Beej126** [comment] 2022-05-31 14:15
@faizansohail077 - just wondering if you had trouble applying working sample on stackblitz?

**Comment by kimberleyrogers** [comment] 2022-07-24 04:17
I started from scratch and followed these steps and thankfully it was resolved. Very easy guide too:
[https://www.alchemy.com/blog/how-to-polyfill-node-core-modules-in-webpack-5](https://www.alchemy.com/blog/how-to-polyfill-node-core-modules-in-webpack-5)

**Comment by CramerJ1470** [comment] 2022-07-25 15:43
ill try these changes in my code and get back you all ! thank you

________________________________

**Comment by CharleneKwok** [comment] 2022-08-05 07:49
> I started from scratch and followed these steps and thankfully it was resolved. Very easy guide too: https://www.alchemy.com/blog/how-to-polyfill-node-core-modules-in-webpack-5

Thank you! This solution works on my project!

**Comment by chaiwattsw** [comment] 2022-08-08 11:29
In my case I have `zlib` and `browserify-zlib` my devDependencies after I removed that dependency everything working fine

**Comment by satinder1624** [comment] 2022-08-08 23:53
Anyone has a solution?

**Comment by CramerJ1470** [comment] 2022-08-09 04:26
I just went in to node_modules/zlib/lib to zlib.js and commented out the code

**Comment by faizansohail077** [comment] 2022-10-11 07:18
Yes I am not being able to resolve this issue. Kindly guide me.how to
resolved this.

**Comment by mukeshrao-cesit** [comment] 2022-11-21 07:25
Compiled with problems:X

ERROR in ./node_modules/destroy/index.js 15:17-41

Module not found: Error: Can't resolve 'fs' in 'C:\Users\mukeshrao.nagendrara\Downloads\React\test\newbie\node_modules\destroy'


ERROR in ./node_modules/etag/index.js 21:12-31

Module not found: Error: Can't resolve 'fs' in 'C:\Users\mukeshrao.nagendrara\Downloads\React\test\newbie\node_modules\etag'


ERROR in ./node_modules/express/lib/view.js 17:9-22

Module not found: Error: Can't resolve 'fs' in 'C:\Users\mukeshrao.nagendrara\Downloads\React\test\newbie\node_modules\express\lib'


ERROR in ./node_modules/mime/mime.js 2:9-22

Module not found: Error: Can't resolve 'fs' in 'C:\Users\mukeshrao.nagendrara\Downloads\React\test\newbie\node_modules\mime'


ERROR in ./node_modules/send/index.js 22:9-22

Module not found: Error: Can't resolve 'fs' in 'C:\Users\mukeshrao.nagendrara\Downloads\React\test\newbie\node_modules\send'


Anyone kindly help me to solve this issue...!

**Comment by CramerJ1470** [comment] 2022-11-23 07:26
mine was within my react app so i changed my react-scripts version from 5.0.1 to 4.0.2 deleted node_modules and packagelock files and did a npm install . i highly recommend creating a duplicate of your entire directory first

**Comment by CramerJ1470** [comment] 2022-11-25 00:14
What version of react-scripts are you using ?

**Comment by CramerJ1470** [comment] 2022-11-28 21:04
I changed my react-scripts version to 4.0.2

**Closed** 2024-02-03 17:51 UTC
