### ISSUE TITLE
Memory leak on Production.

### ISSUE THREAD

**Issue by VrajSolanki** [diegomura/react-pdf#165] opened 2017-12-01 15:32 UTC
Hello @diegomura 
the module suggests it should not be used in Production. What does it exactly implies??

I tried deploying it on AWS, machine using docker container. Now the problem I face is: I observe on each pdf generation it tends to acquire around 70-80mbs of memory and doesn't release even after pdf generation is over and this process goes on.

Can you please suggest, if the module has an issue or I am missing something here??

**Comment by diegomura** [comment] 2018-02-03 20:26
Sorry I didn't respond sooner. Is this still happening?
This is very hard to debug, and I'll need to set up or an AWS machine, or figure out something else.
However, there are points that I think more probably to be the cause of this:

- Yoga: maybe we are missing to free some memory
- FIle I/O

**Comment by rogierslag** [comment] 2018-02-11 20:42
Seems like it definitely is:

<img width="1243" alt="screenshot 2018-02-11 21 41 16" src="https://user-images.githubusercontent.com/2778689/36078252-5add4c68-0f74-11e8-8fce-abf7de251757.png">

After 35 renders I have 35 PDFDocument instances in memory, responsible for 85% of the memory in use by the service.

I think there is a problem in yoga which is called from `measureText` in `Text.js`

**Comment by rogierslag** [comment] 2018-02-11 21:10
I tried ading the master branch of yoga-layout to the project and retesting it with that one, but that produces a very identical result.

We have now "solved" the issue by letting `pm2` issue restarts, but of course that is not the best way to go

**Comment by diegomura** [comment] 2018-02-11 21:22
🤔 Interesting.
Maybe if we call `layout.destroy()` on each node (or in the upper node) after the document is closed? Maybe that will free that memory

**Comment by VrajSolanki** [comment] 2018-02-12 06:12
@diegomura  yes File I/O, and yoga both were leaking memory for me and I used a precompiled version, and also closed the open filestream objects. 
It did fix memory leakage for me but as @rogierslag pointed out it does keep pdfs in memory and thats what takes a major part.

@rogierslag Funny, thats how I too tried to solve the issue.

**Comment by jbovenschen** [comment] 2018-02-12 08:15
The memory leak exists in pdfkit, see https://github.com/devongovett/pdfkit/issues/728. There is an open PR in pdfkit to fix this, but is not merged.

**Comment by diegomura** [comment] 2018-08-02 19:53
Closing this. react-pdf currently uses own pdfkit fork, and no new memory issues were reported ever since.

**Closed by diegomura** 2018-08-02 19:53 UTC
Labels: bug, help wanted
