### ISSUE TITLE
Module not found: Can't resolve 'yoga-layout'  with React 16.14.0 and Node 21

### ISSUE THREAD

**Issue by koranra** [diegomura/react-pdf#2650] opened 2024-02-17 15:20 UTC
**Describe the bug**
Trying to import the library and generate a PDF and am running into issues - Module not found: Can't resolve 'yoga-layout'  with React 16.14.0 and Node 21

**To Reproduce**
attached sample code with a simple example. I followed all the things mentioned in this thread - https://github.com/diegomura/react-pdf/issues/2499.  It works when I use *renderer v3.1.14 and layout v3.6.3**, But it generates a empty pdf. So its breaking with that approach as well.

[sample-app.zip](https://github.com/diegomura/react-pdf/files/14319258/sample-app.zip)

any help would be highly appreciated.

**Comment by andrey-prokhorov** [comment] 2024-02-19 09:30
The same problem with React 18.2 and Node v20.10

**Comment by koranra** [comment] 2024-02-20 00:43
@andrey-prokhorov  it works for me if I upgrade to react 18  with node 21.

**Comment by jgo80** [comment] 2024-02-22 08:22
I encounter the issue client side, packaging my app with Expo/Metro Bundler with the following error:

`Unable to resolve "yoga-layout" from "node_modules/@react-pdf/layout/lib/index.cjs"`

**Comment by PelosiTech** [comment] 2024-02-23 23:35
@jgo80 @koranra @andrey-prokhorov @koranra 

Add this in your package.json

  "resolutions": {
    "@react-pdf/layout": "3.6.4",
    "@react-pdf/textkit": "4.3.0",
    "@react-pdf/pdfkit": "3.1.2"
  }

**Comment by ytreister** [comment] 2024-02-28 16:54
I fixed by adding to my package.json:
```
	"overrides": {
		"@react-pdf/layout": "3.6.4",
		"@react-pdf/textkit": "4.3.0",
		"@react-pdf/image": "2.2.2",
		"@react-pdf/pdfkit": "3.1.2"
	},
```

**Comment by wojtekmaj** [comment] 2024-03-27 07:07
Duplicate of #2499?

**Comment by diegomura** [comment] 2024-11-17 01:27
Seems like it. We are now using yoga-layout@3. Will close this as it seems outdated. Please report back or create a new issue if this persist

**Closed by diegomura** 2024-11-17 01:27 UTC
