### ISSUE TITLE
typeError while loading image in pdf.

### ISSUE THREAD

**Issue by chemseddine201** [diegomura/react-pdf#2025] opened 2022-09-22 19:37 UTC
**TypeError: ctx.embedImage is not a function**
couldn't show an image on the pdf file.
`<Image
            style={{ width: 80, backgroundColor: "red" }}
            fixed
            cache={false} 
            src={mainLogo+"?rnd="+Math.random()} 
       />`
mainLogo: full url of image (string).
_An error shown on the console but the image fully loaded on network tab._
-
`Uncaught (in promise) TypeError: ctx.embedImage is not a function
    at drawImage (index.es.js:1221:1)
    at renderImage (index.es.js:1237:1)
    at renderNode (index.es.js:2021:1)
    at renderChild (index.es.js:2000:1)
    at Array.forEach (<anonymous>)
    at renderChildren (index.es.js:2003:1)
    at renderNode (index.es.js:2022:1)
    at renderChild (index.es.js:2000:1)
    at Array.forEach (<anonymous>)
    at renderChildren (index.es.js:2003:1)
    at renderNode (index.es.js:2022:1)
    at index.es.js:2106:1
    at Array.forEach (<anonymous>)
    at render (index.es.js:2105:1)
    at _callee$ (index.js:34:1)
    at tryCatch (regeneratorRuntime.js:86:1)
    at Generator._invoke (regeneratorRuntime.js:66:1)
    at Generator.next (regeneratorRuntime.js:117:1)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:25:1)`
-
i tried to pass the image a 'blob' and 'base64 string' and same error occurred. any solution ?

**Comment by zeeglenn** [comment] 2022-10-07 18:20
same error here on 3.0.0

**Comment by andresfigueira** [comment] 2022-10-14 13:24
same here. I cannot upgrade to 3.0.0 because of this issue

**Comment by anishpro** [comment] 2022-10-18 09:38
same here

**Comment by bansaj** [comment] 2022-10-20 03:46
This is due to using override for 
"@react-pdf/font": "2.2.1",
    "@react-pdf/pdfkit": "2.1.0"
  Removing these will fix this issue.
  But webpack v4 will give this issue #2015 
  Fix It by upgrading react scripts to v5

**Comment by pwnedev** [comment] 2022-10-27 11:02
> This is due to using override for "@react-pdf/font": "2.2.1", "@react-pdf/pdfkit": "2.1.0" Removing these will fix this issue. But webpack v4 will give this issue #2015 Fix It by upgrading react scripts to v5

Removed override and upgraded to v5. Also dealt with necessary polyfill webpack config and still got the same "ctx.embedImage is not a function" error

**Comment by osbash** [comment] 2022-11-21 18:25
Does anyone have any fix for this using webpack 4?

**Comment by jeetiss** [comment] 2022-12-26 11:39
duplicate of #2089

**Comment by jeetiss** [comment] 2022-12-26 11:40
duplicate of https://github.com/diegomura/react-pdf/issues/2089

**Closed by jeetiss** 2022-12-26 11:40 UTC
