### ISSUE TITLE
@react-pdf/renderer: Support for react@^18

### ISSUE THREAD

**Issue by olnrao** [diegomura/react-pdf#2118] opened 2022-12-23 11:20 UTC
We are using react v18.2.0 and wanted to use @react-pdf/renderer which seems to be hardwired to react@^16 or react@^17.  Here is the issue we have hit:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @react-pdf/renderer@3.0.1
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR!   peer react@"^16.11.0 || ^17 || ^18" from @auth0/auth0-react@1.11.0
npm ERR!   node_modules/@auth0/auth0-react
npm ERR!     @auth0/auth0-react@"^1.11.0" from the root project
npm ERR!   29 more (@emotion/react, @emotion/styled, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.6 || ^17.0.0" from @react-pdf/renderer@3.0.1
npm ERR! node_modules/@react-pdf/renderer
npm ERR!   @react-pdf/renderer@"^3.0.1" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@"^16.8.6 || ^17.0.0" from @react-pdf/renderer@3.0.1
npm ERR!   node_modules/@react-pdf/renderer
npm ERR!     @react-pdf/renderer@"^3.0.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

We have used @react-pdf/renderer with react@^18 and have not hit any issue. 

Because of version-conflict, we are required to use --force flag.  But, we don't want to use force as it is not specific to this package, but all.  Can you please allow react@^18 in your package?

**Comment by jeetiss** [comment] 2022-12-23 12:23
duplicate of https://github.com/diegomura/react-pdf/issues/1878

**Closed by jeetiss** 2022-12-23 12:23 UTC
