### ISSUE TITLE
Can not common install react-pdf on react v18

### ISSUE THREAD

**Issue by DoIttikorn** [diegomura/react-pdf#2133] opened 2023-01-01 10:42 UTC
**Describe the bug**
Can not install common react-pdf on react v18

I still can not to use production app now util this issue fix success

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):

**Expected behavior**
should npm install on react 18

**Screenshots**
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/57912233/210167853-6cd490cf-6ffe-469a-b5c7-2faf6aa70ea1.png">

**Desktop (please complete the following information):**
 - React-pdf version [e.g. v3.0.2]

**Comment by jeetiss** [comment] 2023-01-09 09:42
Duplicate of #1878

**Closed by jeetiss** 2023-01-09 09:42 UTC
