### ISSUE TITLE
Please add support for react 18

### ISSUE THREAD

**Issue by alokjain-lucky** [diegomura/react-pdf#2020] opened 2022-09-19 10:01 UTC
Try installing the preact-pdf package with React 18, it will give you an error 

![image](https://user-images.githubusercontent.com/5526402/190994166-548766ff-b3cc-4fa0-b5da-4f52836d485a.png)

**Comment by chathu-novade** [comment] 2022-09-19 16:49
Duplicate of #1971 , #1878

**Comment by jeetiss** [comment] 2022-12-23 12:22
duplicate of https://github.com/diegomura/react-pdf/issues/1878

**Closed by jeetiss** 2022-12-23 12:22 UTC
